/**
 * HENP App configuration for CoreLib.
 *
 * Phase 3j (v12): SFDC-first effective deployments.
 *  - cfg.sheets.deployments = 'SFDC_Deployments' (canonical source via SOQL)
 *  - cfg.columns.deployments aligned to SFDC_Deployments column positions
 *  - SOQL-side filtering already enforces industry, region, status, and
 *    deployment phase exclusions; APP_CONFIG just registers sheet/columns.
 *
 * NOTE:
 *  - Requires CoreLib library added with identifier "CoreLib".
 *  - Requires TABLES and BAR_CONFIG constants from Code.gs (HENP).
 *  - Industries / regions / phase exclusions live in the Salesforce
 *    connector SOQL, NOT in this config.
 */

/** @type {AppConfig} */
var APP_CONFIG = {
  appId: 'HENP',
  sheets: {
    activeDeployments: 'ActiveDeployments',
    goLives: 'Go Lives',
    deploymentOverrides: 'DeploymentOverrides',
    goLivesOverrides: 'GoLivesOverrides',
    deploymentsMeta: 'DeploymentsMeta',
    changeLog: 'ChangeLog',
    execSummary: 'ExecSummary',
    healthReportSnapshots: 'HealthReportSnapshots',
    healthMonthlySummary: 'HealthMonthlySummary',
    healthYtdSummary: 'HealthYtdSummary',
    dashboard: 'Dashboard',
    appUsers: 'AppUsers',
    ddAssignment: 'DD',
    sfdcDeploymentProductFunctions: 'SFDC_DeploymentProductFunctions',
    deployments: 'SFDC_Deployments',
    deploymentContacts: 'SFDC_DeploymentContacts',
    // T1: Trends history sheet (populated by SOQL)
    deploymentHistory: 'SFDC_DeploymentHistory'
  },
  namedRanges: {
    healthTotal: 'HealthTotal'
  },
  columns: {
    DEPLOYMENT_ID:              1,
    DEPLOYMENT_NAME:            2,
    ACCOUNT_ID:                 3,
    ACCOUNT_NAME:               4,
    INDUSTRY:                   5,
    REGION:                     6,
    SUB_REGION:                 7,
    SUB_REGION_ALT:             8,
    BILLING_STATE:              9,
    BILLING_CITY:              10,
    DEPLOYMENT_START_DATE:     11,
    CURRENT_MTP_DATE:          12,
    FIRST_MTP_DATE:            13,
    OVERALL_STATUS:            14,
    DEPLOYMENT_PHASE:          15,
    DEPLOYMENT_STAGE:          16,
    DEPLOYMENT_HEALTH:         17,
    COMPLETION_DATE:           18,
    WD_ENG_MANAGER:            19,
    DAM_FULL_NAME:             20,
    PRIMING_PARTNER:           21,
    IMPL_PARTNER:              22,
    PARTNER:                   23,
    CURRENT_DEPLOYMENT_UPDATE: 24,
    goLives: {
      ACCOUNT_NAME:        1,
      INDUSTRY:            2,
      DAM_FULL_NAME:       3,
      WD_ENG_MANAGER:      4,
      PARTNER:             5,
      DEPLOYMENT_NAME:     6,
      SERVICES_APPROACH:   7,
      PRODUCT_AREA:        8,
      GO_LIVE_DATE_ACTUAL: 9,
      IN_PRODUCTION:      10
    }
  },
  report: {
    inlineFilename: 'HENP_DeploymentHealth_Dashboard.html',
    outlookFilename: 'HENP_DeploymentHealth_Dashboard_Outlook.html',
    title: 'Higher Education & Non-Profit Deployment Health Report',
    headerLogoUrl: 'https://cdn.brandfetch.io/id0V-YF4nE/w/2048/h/2048/theme/dark/icon.jpeg',
    sanaLogoUrl: 'https://emoji.slack-edge.com/T7U335QS3/sana-labs/1746635f6808c56a.png',
    footerAttribution: 'Generated by the HENP Program Management team',
    tables: TABLES,
    barConfig: BAR_CONFIG,
    goLivesWindowDays: 60,
    redYellowPartnerFilter: null,
    includeIndustryRedYellow: false,
    includeIndustryGoLives: false,
    redYellowOwnerLabel: 'Delivery Director',
    portfolioHealth: {
      title: 'Portfolio Health',
      workdayPartner: 'Workday Professional Services',
      workdayLabel: 'Workday',
      otherLabel: 'Partners/Other',
      recentGoLivesWindowDays: 60,
      industryBuckets: [
        { label: 'Higher Education', match: ['Higher Education'] },
        { label: 'Non-Profit', match: ['Non-Profit'] }
      ]
    }
  },
  salesforce: {
    upcomingWindowDays: 90,
    recentWindowDays: 60,
    statusValues: {
      active: 'Active',
      complete: 'Complete'
    }
  },
  ui: {
    appTitle: 'HENP Deployment Health Manager',
    headerTitle: 'HENP Deployment Health Manager',
    headerSubtitle: 'Review and manage deployment data across all stages',
    tabs: [
      { id: 'deployments', label: 'Deployments' },
      { id: 'golives', label: 'Go Lives' },
      { id: 'execsummary', label: 'Executive Summary' },
      { id: 'report', label: 'Monthly Report Preview' },
      { id: 'portfolio', label: 'Portfolio Health' },
      { id: 'notable', label: 'Notable Deployments' },
      { id: 'overrides', label: 'Manage Overrides' },
      { id: 'trends',    label: 'Trends' }
    ],
    enableAccountLinks: true,
    mgmPglTab: { enabled: false },
    // T1: Trends tab.
    trendsTab: { enabled: true },
    notable: { enabled: true },
    deploymentsTable: {
      showIndustry: false,
      showEmColumn: false,
      ownerColumnLabel: 'Delivery Director',
      showMissingDDHighlight: true,
      missingDDMessage: 'Delivery Director needs assigned',
      searchPlaceholder: 'Search by account, deployment name, partner...',
      defaultHealthFilter: ['Red', 'Yellow'],
      showStageColumn: false,
      expandableRows: true
    },
    goLivesTable: {
      showIndustry: false,
      showProductAreas: true,
      showDeploymentName: false,
      searchPlaceholder: 'Search by account name...'
    },
    goLivesTab: {
      defaultView: 'recent',
      recentWindowDays: 60,
      upcomingWindowDays: 90
    },
    manageOverrides: {
      showAuditTrail: true,
      bulkClearScopes: ['monthly', 'all']
    },
    editModal: {
      ownerFieldLabel: 'Delivery Director',
      ownerInputType: 'text',
      ownerOptions: []
    },
    personalization: {
      enabled: false,
      defaultViewMode: 'allDeployments',
      affectsTabs: ['deployments', 'golives', 'overrides'],
      welcomeMessageEnabled: false,
      showFullPortfolioIndicator: true
    }
  },

  notable: {
    notify: {
      email:               'mariah.maxie@workday.com',
      testEmail:           'jeffrey.ditty@workday.com',
      useTestMode:         true,
      slackWebhookUrl:     '',
      slackWebhookUrlTest: ''
    }
  },

  student: {
    enabled: true,
    productAreaMatch: 'Student',
    sheets: {
      studentData: 'StudentDeploymentData'
    },
    tab: {
      id: 'student',
      label: 'Student',
      insertAfter: 'deployments'
    },
    table: {
      defaultStatusFilter: 'active',
      defaultHealthFilter: null,
      columns: ['account', 'partner', 'currentMtp', 'phase', 'health', 'registrationDate'],
      searchPlaceholder: 'Search Student deployments\u2026',
      expandableRows: true
    },
    editModal: {
      allowedRoles: ['POWER_USER', 'ADMIN'],
      notesMaxChars: 2000
    },
    banner: {
      enabled: true,
      copy: 'Student deployments are not included on this view. See the {Student} tab for all Student deployments and metrics.',
      showOnTabs: ['overview', 'deployments', 'golives', 'reporting', 'portfolio', 'notable'],
      linkToken: '{Student}'
    },
    reportDisclosure: {
      enabled: true,
      copy: 'This report covers HENP Platform deployments only. Student deployments are tracked and reported separately.'
    }
  },

  // ---------------------------------------------------------------------------
  // T1: Trends tab configuration.
  // ---------------------------------------------------------------------------
  trends: {
    cacheTtlSeconds:              3600,
    trendsWindowMonths:           12,
    timeInStageOutlierMultiple:   2,
    timeInStageMinSampleSize:     10,
    byPartnerMinSampleSize:       5
  },

  // ---------------------------------------------------------------------------
  // P2: Portfolio Momentum sub-view configuration.
  // ---------------------------------------------------------------------------
  /** @type {MomentumConfig} */
  momentum: {
    enabled: true,
    platforms: ['HCM', 'FIN', 'PAY', 'STU'],
    productAreaMapping: {
      HCM: ['Core HCM', 'Human Capital Management'],
      FIN: ['Financials', 'Financial Management'],
      PAY: ['Payroll'],
      STU: ['Student']
    },
    historicalYears: 5,  // was 6 — reduced to drop FY21 (incomplete SOQL data)
    chart: {
      colors: {
        HCM: '#0F4C81',
        FIN: '#F46821',
        PAY: '#47E6C1',
        STU: '#A259EA'
      },
      inProgressOpacity: 0.55
    }
  }
};
