/**
 * CoreUI_Css.gs
 *
 * Shared stylesheet for the WebApp UI. Defines a top-level helper function
 * _CoreUI_Css_getStylesheet() that CoreUI.gs calls on demand.
 *
 * Phase history:
 *   Phase 0 (v8): introduced as part of the CoreUI scaffolding.
 *   Phase 1 (v9): full design token system in :root; PH-pattern card design
 *                 across operational tabs.
 *   Phase 2 (v10): adds segmented control, VP/PM dropdown, filter chips,
 *                  More/Fewer filters drawer, expandable row, audit log
 *                  monospace, destructive button variant, welcome/indicator
 *                  banners, Today divider row, confirmation modal styles,
 *                  and header right-region layout for the personalization
 *                  toggle.
 *
 * Approved by Jeff in Phase 2 Design Brief 7joemhuqDkrv on 2026-06-09 14:07 EDT.
 */

var _CoreUI_Css_CACHE = null;

function _CoreUI_Css_getStylesheet() {
  if (_CoreUI_Css_CACHE !== null) return _CoreUI_Css_CACHE;

  _CoreUI_Css_CACHE = [
    // =========================================================================
    // RESET
    // =========================================================================
    '* { margin: 0; padding: 0; box-sizing: border-box; }',

    // =========================================================================
    // DESIGN TOKENS (Phase 1)
    // =========================================================================
    ':root {',
    '  --color-primary: #0F4C81;',
    '  --color-primary-dark: #0A3359;',
    '  --color-primary-tint: #E8EFF6;',
    '  --color-surface: #FFFFFF;',
    '  --color-surface-alt: #F8FAFC;',
    '  --color-border: #E5E7EB;',
    '  --color-border-subtle: #F1F5F9;',
    '  --color-text: #0F172A;',
    '  --color-text-muted: #475569;',
    '  --color-text-subtle: #94A3B8;',
    '  --color-status-green: #10B981;',
    '  --color-status-yellow: #F59E0B;',
    '  --color-status-red: #EF4444;',
    '  --color-status-red-bg: #FEE2E2;',
    '  --color-status-yellow-bg: #FEF3C7;',
    '  --color-status-green-bg: #D1FAE5;',
    '  --color-status-red-fg: #991B1B;',
    '  --color-status-yellow-fg: #92400E;',
    '  --color-status-green-fg: #065F46;',
    '  --color-missing-dd-bg: #FFF1F2;',
    '  --color-info-banner-bg: #EFF6FF;',
    '  --color-info-banner-border: #3B82F6;',
    '  --color-info-banner-text: #1E40AF;',
    '  --space-1: 4px;',
    '  --space-2: 8px;',
    '  --space-3: 12px;',
    '  --space-4: 16px;',
    '  --space-5: 24px;',
    '  --space-6: 32px;',
    '  --space-7: 48px;',
    '  --radius-sm: 4px;',
    '  --radius-md: 8px;',
    '  --radius-lg: 12px;',
    '  --radius-xl: 16px;',
    '  --radius-pill: 999px;',
    '  --shadow-subtle: 0 1px 2px rgba(15, 23, 42, 0.04);',
    '  --shadow-card: 0 2px 8px rgba(15, 23, 42, 0.06);',
    '  --shadow-elevated: 0 8px 24px rgba(15, 23, 42, 0.12);',
    '  --transition-fast: 150ms ease-out;',
    '  --transition-slow: 250ms ease-out;',
    // Legacy aliases — kept for safety; remove in a future cleanup pass.
    '  --primary-color: var(--color-primary);',
    '  --primary-dark: var(--color-primary-dark);',
    '  --secondary-color: var(--color-status-green);',
    '  --danger-color: var(--color-status-red);',
    '  --warning-color: var(--color-status-yellow);',
    '  --text-dark: var(--color-text);',
    '  --text-light: var(--color-text-muted);',
    '  --border-color: var(--color-border);',
    '  --bg-light: var(--color-surface-alt);',
    '  --shadow: var(--shadow-card);',
    '  --shadow-lg: var(--shadow-elevated);',
    '}',

    // =========================================================================
    // BODY + PAGE
    // =========================================================================
    'body {',
    '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Helvetica", "Arial", sans-serif;',
    '  background: var(--color-surface-alt);',
    '  color: var(--color-text);',
    '  line-height: 1.5;',
    '  font-size: 14px;',
    '}',

    // =========================================================================
    // HEADER CARD (Phase 1 + Phase 2 right-region for toggle/dropdown)
    // =========================================================================
    '.header {',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-xl);',
    '  box-shadow: var(--shadow-card);',
    '  margin: var(--space-5) auto var(--space-5) auto;',
    '  max-width: 1400px;',
    '  display: flex;',
    '  align-items: stretch;',
    '  overflow: visible;',                    // ← was hidden
    '  position: sticky;',
    '  top: var(--space-3);',
    '  z-index: 1000;',                        // ← was 100
    '}',
    '.header-strip {',
    '  background: var(--color-primary);',
    '  width: 48px;',
    '  flex-shrink: 0;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  padding: var(--space-4) 0;',
    '  border-top-left-radius: calc(var(--radius-xl) - 1px);',
    '  border-bottom-left-radius: calc(var(--radius-xl) - 1px);',
    '}',
    '.header-strip svg {',
    '  width: 24px;',
    '  height: 24px;',
    '  display: block;',
    '}',
    '.header-body {',
    '  padding: var(--space-4) var(--space-5);',
    '  flex: 1;',
    '  display: flex;',
    '  flex-direction: column;',
    '  justify-content: center;',
    '}',
    '.header-body h1 {',
    '  font-size: 20px;',
    '  font-weight: 600;',
    '  line-height: 1.3;',
    '  color: var(--color-text);',
    '  margin-bottom: 2px;',
    '}',
    '.header-body p {',
    '  font-size: 12px;',
    '  line-height: 1.4;',
    '  color: var(--color-text-muted);',
    '}',
    // Phase 2: right-side region for personalization toggle or dropdown
    '.header-right {',
    '  display: flex;',
    '  align-items: center;',
    '  padding: var(--space-4) var(--space-5) var(--space-4) var(--space-3);',
    '  flex-shrink: 0;',
    '}',

    // =========================================================================
    // CONTAINER + TAB BAR (Phase 1)
    // =========================================================================
    '.container {',
    '  max-width: 1400px;',
    '  margin: 0 auto;',
    '  padding: 0 var(--space-5) var(--space-7) var(--space-5);',
    '}',
    '.tabs {',
    '  display: flex;',
    '  gap: var(--space-1);',
    '  margin-bottom: var(--space-5);',
    '  border-bottom: 1px solid var(--color-border);',
    '  flex-wrap: wrap;',
    '}',
    '.tab {',
    '  padding: var(--space-3) var(--space-4);',
    '  background: transparent;',
    '  border: none;',
    '  border-bottom: 2px solid transparent;',
    '  cursor: pointer;',
    '  font-size: 14px;',
    '  font-weight: 500;',
    '  line-height: 1.5;',
    '  color: var(--color-text-muted);',
    '  transition: color var(--transition-fast), border-color var(--transition-fast);',
    '  margin-bottom: -1px;',
    '  font-family: inherit;',
    '}',
    '.tab:hover { color: var(--color-text); }',
    '.tab.active {',
    '  color: var(--color-primary);',
    '  border-bottom-color: var(--color-primary);',
    '  font-weight: 600;',
    '}',
    '.tab-content { display: none; }',
    '.tab-content.active { display: block; }',

    // =========================================================================
    // INFO BANNERS (Phase 1)
    // =========================================================================
    '.info-banner {',
    '  background: var(--color-info-banner-bg);',
    '  border-left: 4px solid var(--color-info-banner-border);',
    '  padding: var(--space-3) var(--space-4);',
    '  margin-bottom: var(--space-4);',
    '  border-radius: var(--radius-md);',
    '  font-size: 14px;',
    '  line-height: 1.5;',
    '  color: var(--color-info-banner-text);',
    '}',
    '.info-banner strong { font-weight: 600; }',

    // =========================================================================
    // PHASE 2: WELCOME BANNER + FULL-PORTFOLIO INDICATOR BANNER
    // =========================================================================
    '.welcome-banner {',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-left: 4px solid var(--color-primary);',
    '  border-radius: var(--radius-md);',
    '  padding: var(--space-3) var(--space-4);',
    '  margin-bottom: var(--space-4);',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--space-3);',
    '  font-size: 14px;',
    '  line-height: 1.5;',
    '  color: var(--color-text);',
    '  box-shadow: var(--shadow-card);',
    '}',
    '.welcome-banner-content { flex: 1; }',
    '.welcome-banner-close {',
    '  background: transparent;',
    '  border: none;',
    '  font-size: 20px;',
    '  line-height: 1;',
    '  color: var(--color-text-subtle);',
    '  cursor: pointer;',
    '  padding: 0;',
    '  width: 28px;',
    '  height: 28px;',
    '  border-radius: var(--radius-md);',
    '  transition: background var(--transition-fast), color var(--transition-fast);',
    '  font-family: inherit;',
    '}',
    '.welcome-banner-close:hover {',
    '  background: var(--color-surface-alt);',
    '  color: var(--color-text);',
    '}',
    // Full-portfolio indicator banner — used on PH and Monthly Report Preview
    '.full-portfolio-indicator {',
    '  background: var(--color-surface-alt);',
    '  border: 1px solid var(--color-border-subtle);',
    '  border-radius: var(--radius-md);',
    '  padding: var(--space-2) var(--space-3);',
    '  margin-bottom: var(--space-3);',
    '  font-size: 12px;',
    '  color: var(--color-text-muted);',
    '}',

    // =========================================================================
    // PHASE 2: SEGMENTED CONTROL (personalization toggle + Go Lives toggle)
    // =========================================================================
    '.seg-control {',
    '  display: inline-flex;',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-md);',
    '  overflow: hidden;',
    '  background: var(--color-surface);',
    '}',
    '.seg-control-btn {',
    '  padding: var(--space-2) var(--space-3);',
    '  background: transparent;',
    '  border: none;',
    '  color: var(--color-text-muted);',
    '  font-size: 13px;',
    '  font-weight: 500;',
    '  line-height: 1.4;',
    '  cursor: pointer;',
    '  transition: background var(--transition-fast), color var(--transition-fast);',
    '  font-family: inherit;',
    '  white-space: nowrap;',
    '}',
    '.seg-control-btn + .seg-control-btn {',
    '  border-left: 1px solid var(--color-border);',
    '}',
    '.seg-control-btn:hover {',
    '  color: var(--color-text);',
    '  background: var(--color-surface-alt);',
    '}',
    '.seg-control-btn.active {',
    '  background: var(--color-primary);',
    '  color: #ffffff;',
    '  font-weight: 600;',
    '}',
    '.seg-control-btn.active:hover { background: var(--color-primary-dark); }',

    // =========================================================================
    // PHASE 2: VP/PM DROPDOWN SELECTOR (right side of header)
    // =========================================================================
    '.dd-dropdown {',
    '  position: relative;',
    '  display: inline-block;',
    '}',
    '.dd-dropdown-trigger {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--space-2);',
    '  padding: var(--space-2) var(--space-3);',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-md);',
    '  font-size: 13px;',
    '  font-weight: 500;',
    '  color: var(--color-text);',
    '  cursor: pointer;',
    '  transition: background var(--transition-fast), border-color var(--transition-fast);',
    '  font-family: inherit;',
    '  white-space: nowrap;',
    '}',
    '.dd-dropdown-trigger:hover { background: var(--color-surface-alt); }',
    '.dd-dropdown-trigger .caret {',
    '  font-size: 10px;',
    '  color: var(--color-text-subtle);',
    '}',
    '.dd-dropdown-menu {',
    '  position: absolute;',
    '  top: calc(100% + 4px);',
    '  right: 0;',
    '  min-width: 220px;',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-md);',
    '  box-shadow: var(--shadow-elevated);',
    '  z-index: 2000;',
    '  overflow: hidden;',
    '  display: none;',
    '}',
    '.dd-dropdown.open .dd-dropdown-menu { display: block; }',
    '.dd-dropdown-option {',
    '  padding: var(--space-2) var(--space-3);',
    '  font-size: 13px;',
    '  color: var(--color-text);',
    '  cursor: pointer;',
    '  transition: background var(--transition-fast);',
    '}',
    '.dd-dropdown-option:hover { background: var(--color-surface-alt); }',
    '.dd-dropdown-option.selected {',
    '  background: var(--color-primary-tint);',
    '  color: var(--color-primary);',
    '  font-weight: 600;',
    '}',

    // =========================================================================
    // STATS / KPI CARDS (Phase 1) + Phase 2 green variant
    // =========================================================================
    '.stats-grid {',
    '  display: grid;',
    '  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));',
    '  gap: var(--space-4);',
    '  margin-bottom: var(--space-4);',
    '}',
    '.stat-card {',
    '  position: relative;',
    '  overflow: hidden;',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-lg);',
    '  box-shadow: var(--shadow-card);',
    '  padding: var(--space-4) var(--space-4);',
    '  transition: opacity var(--transition-fast);',
    '}',
    '.stat-card::before {',
    '  content: "";',
    '  position: absolute;',
    '  top: 0; left: 0; right: 0;',
    '  height: 3px;',
    '  background: var(--color-primary);',
    '}',
    '.stat-card.red::before    { background: var(--color-status-red); }',
    '.stat-card.yellow::before { background: var(--color-status-yellow); }',
    '.stat-card.green::before  { background: var(--color-status-green); }',
    '.stat-card h3 {',
    '  font-size: 13px;',
    '  font-weight: 700;',
    '  line-height: 1.4;',
    '  color: var(--color-text-muted);',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.6px;',
    '  margin-bottom: var(--space-2);',
    '}',
    '.stat-card .value {',
    '  font-size: 32px;',
    '  font-weight: 700;',
    '  line-height: 1.1;',
    '  color: var(--color-text);',
    '}',
    '.stat-card .sub {',
    '  font-size: 12px;',
    '  line-height: 1.4;',
    '  color: var(--color-text-subtle);',
    '  margin-top: var(--space-1);',
    '}',

    // =========================================================================
    // FILTER BAR (Phase 1 base) + Phase 2 chips and More-filters drawer
    // =========================================================================
    '.control-bar {',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-lg);',
    '  box-shadow: var(--shadow-card);',
    '  padding: var(--space-3);',
    '  margin-bottom: var(--space-4);',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: var(--space-3);',
    '}',
    '.control-row {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--space-3);',
    '  flex-wrap: wrap;',
    '}',
    '.search-box {',
    '  flex: 1;',
    '  min-width: 250px;',
    '  position: relative;',
    '  display: flex;',
    '  align-items: center;',
    '}',
    '.search-box input {',
    '  width: 100%;',
    '  padding: var(--space-2) var(--space-3) var(--space-2) 36px;',
    '  border: none;',
    '  background: transparent;',
    '  border-radius: var(--radius-md);',
    '  font-size: 14px;',
    '  line-height: 1.5;',
    '  color: var(--color-text);',
    '  transition: background var(--transition-fast);',
    '  font-family: inherit;',
    '}',
    '.search-box input::placeholder { color: var(--color-text-subtle); }',
    '.search-box input:focus {',
    '  outline: none;',
    '  background: var(--color-surface-alt);',
    '}',
    '.search-icon {',
    '  position: absolute;',
    '  left: var(--space-3);',
    '  top: 50%;',
    '  transform: translateY(-50%);',
    '  font-size: 16px;',
    '  color: var(--color-text-subtle);',
    '  pointer-events: none;',
    '}',
    '.filter-group {',
    '  display: flex;',
    '  gap: var(--space-2);',
    '  align-items: center;',
    '  flex-wrap: wrap;',
    '}',
    // Filter chip group label
    '.filter-label {',
    '  font-size: 13px;',
    '  font-weight: 500;',
    '  color: var(--color-text-muted);',
    '  white-space: nowrap;',
    '}',
    // Phase 2: filter chips
    '.filter-chip {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--space-1);',
    '  padding: 4px var(--space-2);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-pill);',
    '  background: var(--color-surface);',
    '  color: var(--color-text-muted);',
    '  font-size: 12px;',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '  transition: background var(--transition-fast), color var(--transition-fast), border-color var(--transition-fast);',
    '  font-family: inherit;',
    '  white-space: nowrap;',
    '}',
    '.filter-chip:hover {',
    '  border-color: var(--color-text-muted);',
    '  color: var(--color-text);',
    '}',
    '.filter-chip.active {',
    '  background: var(--color-primary);',
    '  color: #ffffff;',
    '  border-color: var(--color-primary);',
    '}',
    '.filter-chip.active:hover {',
    '  background: var(--color-primary-dark);',
    '  border-color: var(--color-primary-dark);',
    '}',
    '.filter-chip .chip-mark {',
    '  font-size: 10px;',
    '  line-height: 1;',
    '  opacity: 0.85;',
    '}',
    // Phase 2: Filter dropdown (Owner, Partner, Stage, Industry)
    '.filter-select {',
    '  padding: 4px var(--space-2);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-md);',
    '  background: var(--color-surface);',
    '  color: var(--color-text);',
    '  font-size: 13px;',
    '  font-family: inherit;',
    '  cursor: pointer;',
    '}',
    '.filter-select:focus {',
    '  outline: none;',
    '  border-color: var(--color-primary);',
    '  box-shadow: 0 0 0 3px var(--color-primary-tint);',
    '}',
    // Phase 2: More/Fewer filters drawer button
    '.filter-drawer-toggle {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--space-1);',
    '  padding: 4px var(--space-3);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-pill);',
    '  background: var(--color-surface-alt);',
    '  color: var(--color-text-muted);',
    '  font-size: 12px;',
    '  font-weight: 500;',
    '  cursor: pointer;',
    '  transition: background var(--transition-fast), color var(--transition-fast);',
    '  font-family: inherit;',
    '}',
    '.filter-drawer-toggle:hover { background: var(--color-border); color: var(--color-text); }',
    '.filter-drawer-toggle .badge {',
    '  background: var(--color-primary);',
    '  color: #ffffff;',
    '  border-radius: var(--radius-pill);',
    '  padding: 0 6px;',
    '  font-size: 10px;',
    '  font-weight: 700;',
    '  margin-left: 4px;',
    '}',
    // Drawer content row
    '.filter-drawer {',
    '  display: none;',
    '  flex-wrap: wrap;',
    '  gap: var(--space-3);',
    '  padding-top: var(--space-2);',
    '  border-top: 1px dashed var(--color-border-subtle);',
    '  align-items: center;',
    '}',
    '.filter-drawer.open { display: flex; }',

    // =========================================================================
    // BUTTONS (Phase 1) + Phase 2 destructive variant
    // =========================================================================
    '.btn {',
    '  padding: var(--space-3) var(--space-4);',
    '  border: 1px solid transparent;',
    '  border-radius: var(--radius-md);',
    '  font-size: 13px;',
    '  font-weight: 600;',
    '  line-height: 1.4;',
    '  cursor: pointer;',
    '  transition: background var(--transition-fast), border-color var(--transition-fast), color var(--transition-fast);',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--space-2);',
    '  font-family: inherit;',
    '}',
    '.btn-primary {',
    '  background: var(--color-primary);',
    '  color: #ffffff;',
    '  border-color: var(--color-primary);',
    '}',
    '.btn-primary:hover { background: var(--color-primary-dark); border-color: var(--color-primary-dark); }',
    '.btn-secondary {',
    '  background: var(--color-surface);',
    '  color: var(--color-text);',
    '  border-color: var(--color-border);',
    '}',
    '.btn-secondary:hover { background: var(--color-surface-alt); }',
    '.control-bar .btn-secondary {',
    '  border-radius: var(--radius-pill);',
    '  padding: var(--space-2) var(--space-4);',
    '  font-size: 12px;',
    '  color: var(--color-text-muted);',
    '  background: var(--color-surface-alt);',
    '}',
    '.control-bar .btn-secondary:hover { background: var(--color-border); color: var(--color-text); }',
    // Phase 2: destructive variant
    '.btn-destructive {',
    '  background: var(--color-surface);',
    '  color: var(--color-status-red-fg);',
    '  border-color: var(--color-status-red);',
    '}',
    '.btn-destructive:hover {',
    '  background: var(--color-status-red);',
    '  color: #ffffff;',
    '  border-color: var(--color-status-red);',
    '}',
    // Strong destructive — used for "Clear all overrides" (nuclear option)
    '.btn-destructive-strong {',
    '  background: var(--color-surface);',
    '  color: var(--color-status-red-fg);',
    '  border-color: var(--color-status-red);',
    '  font-weight: 700;',
    '}',
    '.btn-destructive-strong:hover {',
    '  background: var(--color-status-red);',
    '  color: #ffffff;',
    '  border-color: var(--color-status-red);',
    '}',

    // =========================================================================
    // TABLES (Phase 1) + Phase 2 expandable rows + Phase 2 chevron column
    // =========================================================================
    '.table-container {',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-lg);',
    '  box-shadow: var(--shadow-card);',
    '  overflow: hidden;',
    '}',
    '.table-wrapper { overflow-x: auto; }',
    'table {',
    '  width: 100%;',
    '  border-collapse: collapse;',
    '  font-size: 14px;',
    '}',
    'thead { background: var(--color-surface-alt); position: sticky; top: 0; }',
    'th {',
    '  padding: var(--space-3) var(--space-4);',
    '  text-align: left;',
    '  font-size: 12px;',
    '  font-weight: 600;',
    '  line-height: 1.4;',
    '  color: var(--color-text-muted);',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '  border-bottom: 1px solid var(--color-border);',
    '  white-space: nowrap;',
    '}',
    'td {',
    '  padding: var(--space-3) var(--space-4);',
    '  border-bottom: 1px solid var(--color-border-subtle);',
    '  color: var(--color-text);',
    '  vertical-align: middle;',
    '}',
    'tbody tr { transition: background-color var(--transition-fast); }',
    'tbody tr:not(.missing-dd-row):hover { background: var(--color-surface-alt); }',
    'tbody tr.missing-dd-row { background-color: var(--color-missing-dd-bg) !important; }',
    'tbody tr:last-child td { border-bottom: none; }',

    // Phase 2: clickable rows (expandable Deployments tab)
    'tbody tr.expandable-row { cursor: pointer; }',
    'tbody tr.expandable-row .row-chevron {',
    '  display: inline-block;',
    '  width: 14px;',
    '  text-align: center;',
    '  color: var(--color-text-subtle);',
    '  font-size: 10px;',
    '  transition: transform var(--transition-fast), color var(--transition-fast);',
    '}',
    'tbody tr.expandable-row:hover .row-chevron { color: var(--color-text-muted); }',
    'tbody tr.expandable-row.expanded .row-chevron {',
    '  transform: rotate(90deg);',
    '  color: var(--color-primary);',
    '}',
    // The expanded detail row (rendered as a separate <tr> with a single colspan'd td)
    'tbody tr.row-detail td {',
    '  padding: 0;',
    '  background: var(--color-surface-alt);',
    '}',
    '.row-detail-card {',
    '  padding: var(--space-4) var(--space-5);',
    '  display: grid;',
    '  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));',
    '  gap: var(--space-3) var(--space-5);',
    '  font-size: 13px;',
    '}',
    '.row-detail-card .detail-label {',
    '  display: block;',
    '  font-size: 11px;',
    '  font-weight: 600;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '  color: var(--color-text-muted);',
    '  margin-bottom: 2px;',
    '}',
    '.row-detail-card .detail-value {',
    '  color: var(--color-text);',
    '  word-wrap: break-word;',
    '}',
    '.row-detail-card .detail-full-width { grid-column: 1 / -1; }',
    '.row-detail-card .detail-actions {',
    '  grid-column: 1 / -1;',
    '  display: flex;',
    '  gap: var(--space-2);',
    '  margin-top: var(--space-2);',
    '}',

    // Status pills (Phase 1)
    '.status-badge {',
    '  display: inline-block;',
    '  padding: 2px var(--space-2);',
    '  border-radius: var(--radius-pill);',
    '  font-size: 11px;',
    '  font-weight: 700;',
    '  letter-spacing: 0.5px;',
    '  text-transform: uppercase;',
    '  line-height: 1.3;',
    '}',
    '.status-yellow { background: var(--color-status-yellow-bg); color: var(--color-status-yellow-fg); }',
    '.status-red    { background: var(--color-status-red-bg);    color: var(--color-status-red-fg); }',
    '.status-green  { background: var(--color-status-green-bg);  color: var(--color-status-green-fg); }',

    // Action button (Phase 1)
    '.action-btn {',
    '  padding: var(--space-1) var(--space-3);',
    '  font-size: 12px;',
    '  font-weight: 500;',
    '  background: transparent;',
    '  border: 1px solid var(--color-border);',
    '  color: var(--color-text-muted);',
    '  border-radius: var(--radius-md);',
    '  cursor: pointer;',
    '  transition: background var(--transition-fast), color var(--transition-fast), border-color var(--transition-fast);',
    '  font-family: inherit;',
    '}',
    '.action-btn:hover {',
    '  background: var(--color-primary);',
    '  color: #ffffff;',
    '  border-color: var(--color-primary);',
    '}',

    // Meta indicator (Phase 1)
    '.meta-indicator {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: 18px;',
    '  height: 18px;',
    '  border-radius: 50%;',
    '  background-color: var(--color-primary);',
    '  color: #ffffff;',
    '  font-size: 10px;',
    '  font-weight: 700;',
    '  margin-right: var(--space-1);',
    '  cursor: pointer;',
    '  transition: background var(--transition-fast);',
    '}',
    '.meta-indicator:hover { background-color: var(--color-primary-dark); }',

    // =========================================================================
    // PHASE 2: TODAY DIVIDER ROW (Go Lives All-mode timeline)
    // =========================================================================
    'tbody tr.today-divider td {',
    '  background: var(--color-surface-alt);',
    '  color: var(--color-text-subtle);',
    '  text-align: center;',
    '  font-style: italic;',
    '  font-size: 12px;',
    '  padding: var(--space-2) var(--space-3);',
    '  border-bottom: none;',
    '  border-top: 1px dashed var(--color-border);',
    '}',

    // =========================================================================
    // PHASE 2: MANAGE OVERRIDES — section cards + audit log + action pills
    // =========================================================================
    '.overrides-section {',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-lg);',
    '  box-shadow: var(--shadow-card);',
    '  padding: var(--space-4) var(--space-5);',
    '  margin-bottom: var(--space-4);',
    '}',
    '.overrides-section-title {',
    '  font-size: 13px;',
    '  font-weight: 700;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.6px;',
    '  color: var(--color-text-muted);',
    '  margin-bottom: var(--space-3);',
    '}',
    '.overrides-warning {',
    '  margin-top: var(--space-3);',
    '  padding: var(--space-2) var(--space-3);',
    '  background: var(--color-status-yellow-bg);',
    '  color: var(--color-status-yellow-fg);',
    '  border-radius: var(--radius-md);',
    '  font-size: 12px;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--space-2);',
    '}',
    '.bulk-actions {',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: var(--space-2);',
    '  align-items: flex-start;',
    '}',
    // Type pill (Deploy / Go Lives) in active overrides table
    '.type-pill {',
    '  display: inline-block;',
    '  padding: 2px var(--space-2);',
    '  border-radius: var(--radius-pill);',
    '  font-size: 11px;',
    '  font-weight: 700;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '  background: var(--color-surface-alt);',
    '  color: var(--color-text-muted);',
    '}',
    '.type-pill.deploy { background: var(--color-primary-tint); color: var(--color-primary); }',
    '.type-pill.golives { background: var(--color-status-green-bg); color: var(--color-status-green-fg); }',
    // Classification pill (Monthly / Structural)
    '.classification-pill {',
    '  display: inline-block;',
    '  padding: 2px var(--space-2);',
    '  border-radius: var(--radius-pill);',
    '  font-size: 11px;',
    '  font-weight: 700;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '  cursor: pointer;',
    '  transition: background var(--transition-fast);',
    '}',
    '.classification-pill.monthly { background: var(--color-info-banner-bg); color: var(--color-info-banner-text); }',
    '.classification-pill.structural { background: var(--color-status-yellow-bg); color: var(--color-status-yellow-fg); }',
    '.classification-pill:hover { opacity: 0.85; }',
    // Audit log monospace (per H9)
    '.audit-log td.audit-mono, .audit-log th.audit-mono {',
    '  font-family: "Menlo", "Monaco", "Courier New", monospace;',
    '  font-size: 12px;',
    '}',
    // Audit action pills
    '.audit-action-pill {',
    '  display: inline-block;',
    '  padding: 2px var(--space-2);',
    '  border-radius: var(--radius-pill);',
    '  font-size: 10px;',
    '  font-weight: 700;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '}',
    '.audit-action-pill.create     { background: var(--color-status-green-bg); color: var(--color-status-green-fg); }',
    '.audit-action-pill.update     { background: var(--color-info-banner-bg);  color: var(--color-info-banner-text); }',
    '.audit-action-pill.clear      { background: var(--color-status-yellow-bg); color: var(--color-status-yellow-fg); }',
    '.audit-action-pill.bulk_clear { background: var(--color-status-red-bg);   color: var(--color-status-red-fg); }',

    // =========================================================================
    // PHASE 3a: Phased pill + Portfolio Health phased KPI tile
    // =========================================================================
    // Phased badge — appears inline with deployment name in Deployments tab
    // and in the GoLives Upcoming tab for multi-date rows.
    '.phased-pill {',
    '  display: inline-block;',
    '  padding: 1px 7px;',
    '  border-radius: var(--radius-pill);',
    '  font-size: 10px;',
    '  font-weight: 700;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '  background: #ede9fe;',
    '  color: #6d28d9;',
    '  margin-left: 4px;',
    '  vertical-align: middle;',
    '  white-space: nowrap;',
    '}',
         // Phase 3a — Multi-date phased deployment rendering (defensive selectors)
    '#golives-tbody td > div,',
    '#deployments-tbody td > div {',
    '  padding: var(--space-1) 0;',
    '  line-height: 1.5;',
    '}',
    '#golives-tbody td > div + div,',
    '#deployments-tbody td > div + div {',
    '  border-top: 1px dashed var(--color-border-subtle);',
    '  margin-top: var(--space-2);',
    '  padding-top: var(--space-2);',
    '}',
    '#golives-tbody td strong,',
    '#deployments-tbody td strong {',
    '  font-weight: 600;',
    '  color: var(--color-text);',
    '  margin-right: var(--space-1);',
    '}',
    '/* Phase 3a-css: stable class hooks for phased multi-date Go Lives cells */',
    '.golives-date-cell { vertical-align: top; }',
    '.golives-date-entry {',
    '  padding: var(--space-1) 0;',
    '  line-height: 1.5;',
    '}',
    '.golives-date-entry + .golives-date-entry {',
    '  border-top: 1px dashed var(--color-border-subtle);',
    '  margin-top: var(--space-2);',
    '  padding-top: var(--space-2);',
    '}',
    '.golives-date-label {',
    '  display: block;',
    '  font-weight: 600;',
    '  color: var(--color-text);',
    '}',
    '.golives-product-list {',
    '  display: block;',
    '  font-size: 12px;',
    '  color: var(--color-text-muted);',
    '  margin-top: 2px;',
    '  line-height: 1.4;',
    '}',
    
    // Phased KPI tile accent (purple top border)
    '.ph-kpi.phased::before { background: #6d28d9; }',

    // =========================================================================
    // MODALS (Phase 1) + Phase 2 confirmation modal variant
    // =========================================================================
    '.modal-overlay {',
    '  display: none;',
    '  position: fixed;',
    '  top: 0; left: 0; right: 0; bottom: 0;',
    '  background: rgba(15, 23, 42, 0.5);',
    '  z-index: 1000;',
    '  align-items: center;',
    '  justify-content: center;',
    '  animation: fadeIn var(--transition-slow);',
    '}',
    '.modal-overlay.active { display: flex; }',
    '@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }',
    '.modal {',
    '  background: var(--color-surface);',
    '  border-radius: var(--radius-xl);',
    '  box-shadow: var(--shadow-elevated);',
    '  width: 90%;',
    '  max-width: 800px;',
    '  max-height: 90vh;',
    '  overflow-y: auto;',
    '  animation: slideUp var(--transition-slow);',
    '}',
    '@keyframes slideUp { from { transform: translateY(20px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }',
    // Smaller modal for confirmations
    '.modal.modal-sm { max-width: 500px; }',
    '.modal-header {',
    '  padding: var(--space-5) var(--space-5) var(--space-4) var(--space-5);',
    '  border-bottom: 1px solid var(--color-border-subtle);',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '}',
    '.modal-header h2 {',
    '  font-size: 15px;',
    '  font-weight: 700;',
    '  line-height: 1.3;',
    '  color: var(--color-text);',
    '}',
    '.modal-close {',
    '  background: transparent;',
    '  border: none;',
    '  font-size: 22px;',
    '  line-height: 1;',
    '  color: var(--color-text-subtle);',
    '  cursor: pointer;',
    '  padding: 0;',
    '  width: 28px;',
    '  height: 28px;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  border-radius: var(--radius-md);',
    '  transition: background var(--transition-fast), color var(--transition-fast);',
    '  font-family: inherit;',
    '}',
    '.modal-close:hover { background: var(--color-surface-alt); color: var(--color-text); }',
    '.modal-body { padding: var(--space-5); }',
    '.modal-body p + p { margin-top: var(--space-3); }',
    '.modal-body .modal-list {',
    '  margin: var(--space-3) 0;',
    '  padding-left: var(--space-5);',
    '  color: var(--color-text-muted);',
    '  font-size: 13px;',
    '}',
    '.modal-body .modal-list li { padding: 2px 0; }',
    '.modal-footer {',
    '  padding: var(--space-4) var(--space-5);',
    '  border-top: 1px solid var(--color-border-subtle);',
    '  display: flex;',
    '  justify-content: flex-end;',
    '  gap: var(--space-2);',
    '}',
    // Phase 2: Classification selector inside edit modal
    '.classification-selector {',
    '  display: flex;',
    '  gap: var(--space-3);',
    '  align-items: center;',
    '  font-size: 13px;',
    '}',
    '.classification-selector label {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--space-1);',
    '  cursor: pointer;',
    '  color: var(--color-text);',
    '}',
    '.classification-selector input[type="radio"] {',
    '  cursor: pointer;',
    '  accent-color: var(--color-primary);',
    '}',

    // =========================================================================
    // FORMS (Phase 1)
    // =========================================================================
    '.form-grid {',
    '  display: grid;',
    '  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));',
    '  gap: var(--space-4);',
    '}',
    '.form-group {',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: var(--space-1);',
    '}',
    '.form-group.full-width { grid-column: 1 / -1; }',
    '.form-label {',
    '  font-size: 13px;',
    '  font-weight: 500;',
    '  line-height: 1.4;',
    '  color: var(--color-text-muted);',
    '}',
    '.form-input, .form-select, .form-textarea {',
    '  padding: var(--space-3);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-md);',
    '  font-size: 14px;',
    '  line-height: 1.5;',
    '  color: var(--color-text);',
    '  background: var(--color-surface);',
    '  transition: border-color var(--transition-fast), box-shadow var(--transition-fast);',
    '  font-family: inherit;',
    '}',
    '.form-input:focus, .form-select:focus, .form-textarea:focus {',
    '  outline: none;',
    '  border-color: var(--color-primary);',
    '  box-shadow: 0 0 0 3px var(--color-primary-tint);',
    '}',
    '.form-input[readonly] { background: var(--color-surface-alt); color: var(--color-text-muted); }',
    '.form-textarea { min-height: 100px; resize: vertical; }',

    // =========================================================================
    // SPINNER + LOADING STATES (Phase 1)
    // =========================================================================
    '.spinner {',
    '  display: inline-block;',
    '  width: 14px;',
    '  height: 14px;',
    '  border: 2px solid rgba(255,255,255,0.4);',
    '  border-top-color: #ffffff;',
    '  border-radius: 50%;',
    '  animation: spin 0.6s linear infinite;',
    '}',
    '@keyframes spin { to { transform: rotate(360deg); } }',
    '.report-loading {',
    '  text-align: center;',
    '  padding: var(--space-7) var(--space-5);',
    '  color: var(--color-text-muted);',
    '}',
    '.report-loading .spinner-large {',
    '  display: inline-block;',
    '  width: 40px;',
    '  height: 40px;',
    '  border: 3px solid var(--color-primary-tint);',
    '  border-top-color: var(--color-primary);',
    '  border-radius: 50%;',
    '  animation: spin 0.8s linear infinite;',
    '  margin-bottom: var(--space-3);',
    '}',
    '.empty-state {',
    '  text-align: center;',
    '  padding: var(--space-7) var(--space-5);',
    '  color: var(--color-text-subtle);',
    '  font-size: 14px;',
    '}',
    '.empty-state .empty-state-action {',
    '  margin-top: var(--space-3);',
    '}',

    // =========================================================================
    // REPORT PREVIEW (Phase 1)
    // =========================================================================
    '#report-preview-container {',
    '  background: var(--color-surface);',
    '  overflow-x: auto;',
    '}',
    '#report-preview-container iframe {',
    '  width: 100%;',
    '  min-height: 800px;',
    '  border: none;',
    '}',

    // =========================================================================
    // TOASTS (Phase 1)
    // =========================================================================
    '.toast {',
    '  position: fixed;',
    '  bottom: var(--space-5);',
    '  right: var(--space-5);',
        '  background: var(--color-surface);',
    '  padding: var(--space-3) var(--space-4);',
    '  border-radius: var(--radius-md);',
    '  box-shadow: var(--shadow-elevated);',
    '  border: 1px solid var(--color-border);',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--space-2);',
    '  z-index: 2000;',
    '  font-size: 14px;',
    '  color: var(--color-text);',
    '  animation: slideIn var(--transition-slow);',
    '  border-left-width: 4px;',
    '}',
    '@keyframes slideIn { from { transform: translateX(400px); opacity: 0; } to { transform: translateX(0); opacity: 1; } }',
    '.toast.success { border-left-color: var(--color-status-green); }',
    '.toast.error   { border-left-color: var(--color-status-red); }',

    '.hidden { display: none !important; }',

    // =========================================================================
    // RESPONSIVE
    // =========================================================================
    '@media (max-width: 768px) {',
    '  .container { padding: 0 var(--space-3) var(--space-5) var(--space-3); }',
    '  .header { margin: var(--space-3) var(--space-3); }',
    '  .header-right { padding: var(--space-3); }',
    '  .control-bar { padding: var(--space-3); }',
    '  .control-row { flex-direction: column; align-items: stretch; }',
    '  .search-box { width: 100%; }',
    '  .modal { width: 95%; margin: var(--space-3); }',
    '  .modal.modal-sm { width: 95%; }',
    '  .form-grid { grid-template-columns: 1fr; }',
    '}',

    // =========================================================================
    // PORTFOLIO HEALTH TAB (unchanged from Phase 1)
    // =========================================================================
    '.ph-toolbar {',
    '  display: flex;',
    '  justify-content: flex-end;',
    '  margin-bottom: var(--space-3);',
    '  max-width: 1200px;',
    '  margin-left: auto;',
    '  margin-right: auto;',
    '}',
    '.ph-canvas {',
    '  background: var(--color-surface-alt);',
    '  padding: var(--space-5);',
    '  border-radius: var(--radius-lg);',
    '  border: 1px solid var(--color-border);',
    '  color: var(--color-text);',
    '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;',
    '  max-width: 1200px;',
    '  margin: 0 auto;',
    '}',
    '#portfolio-tab .info-banner {',
    '  max-width: 1200px;',
    '  margin-left: auto;',
    '  margin-right: auto;',
    '}',

    '.ph-header {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  padding: 14px 18px;',
    '  background: var(--color-primary);',
    '  color: #fff;',
    '  border-radius: 10px;',
    '  margin-bottom: 18px;',
    '}',
    '.ph-header .ph-title { font-size: 18px; font-weight: 700; letter-spacing: 0.2px; }',
    '.ph-header .ph-meta { font-size: 12px; opacity: 0.9; }',

    '.ph-kpis {',
    '  display: grid;',
    '  grid-template-columns: repeat(5, 1fr);',
    '  gap: 12px;',
    '  margin-bottom: 18px;',
    '}',
    '.ph-kpi {',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-lg);',
    '  padding: 14px 16px;',
    '  position: relative;',
    '  overflow: hidden;',
    '}',
    '.ph-kpi::before {',
    '  content: "";',
    '  position: absolute;',
    '  top: 0; left: 0; right: 0;',
    '  height: 3px;',
    '  background: var(--color-primary);',
    '}',
    '.ph-kpi.green::before  { background: var(--color-status-green); }',
    '.ph-kpi.yellow::before { background: var(--color-status-yellow); }',
    '.ph-kpi.red::before    { background: var(--color-status-red); }',
    '.ph-kpi .ph-kpi-label  { font-size: 11px; color: var(--color-text-muted); text-transform: uppercase; letter-spacing: 0.6px; font-weight: 600; }',
    '.ph-kpi .ph-kpi-value  { font-size: 32px; font-weight: 700; margin-top: 4px; color: var(--color-text); }',
    '.ph-kpi .ph-kpi-sub    { font-size: 12px; color: var(--color-text-subtle); margin-top: 2px; }',
    '.ph-kpi-row {',
    '  display: flex; align-items: center; justify-content: space-between;',
    '  gap: 8px; margin-top: 2px;',
    '}',

    '.ph-trend {',
    '  display: inline-flex; align-items: center; gap: 3px;',
    '  font-size: 11px; font-weight: 700;',
    '  padding: 2px 7px; border-radius: var(--radius-pill);',
    '  background: var(--color-surface-alt); color: var(--color-text-muted);',
    '  white-space: nowrap;',
    '}',
    '.ph-trend.good { background: var(--color-status-green-bg); color: var(--color-status-green-fg); }',
    '.ph-trend.bad  { background: var(--color-status-red-bg);   color: var(--color-status-red-fg); }',
    '.ph-trend.flat { background: var(--color-surface-alt);     color: var(--color-text-muted); }',
    '.ph-trend .ph-arrow { font-size: 10px; line-height: 1; }',

    '.ph-spark { width: 100%; height: 28px; margin-top: 8px; display: block; }',
    '.ph-spark .ph-spark-line { fill: none; stroke-width: 1.6; }',
    '.ph-spark .ph-spark-area { opacity: 0.18; stroke: none; }',
    '.ph-spark .ph-spark-dot  { stroke: #fff; stroke-width: 1.4; }',

    '.ph-grid { display: grid; grid-template-columns: 320px 1fr; gap: 16px; }',
    '.ph-col  { display: flex; flex-direction: column; gap: 16px; }',
    '.ph-card {',
    '  background: var(--color-surface); border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-lg); padding: 16px 18px;',
    '}',
    '.ph-card-title {',
    '  font-size: 13px; font-weight: 700;',
    '  color: var(--color-text); text-transform: uppercase;',
    '  letter-spacing: 0.6px; margin-bottom: 10px;',
    '  display: flex; align-items: center; justify-content: space-between;',
    '}',
    '.ph-card-title .ph-count {',
    '  background: var(--color-surface-alt); color: var(--color-text-muted);',
    '  font-size: 11px; font-weight: 700;',
    '  padding: 2px 8px; border-radius: var(--radius-pill);',
    '}',

    '.ph-list { display: flex; flex-direction: column; gap: 6px; }',
    '.ph-list-item {',
    '  display: flex; align-items: center; gap: 8px;',
    '  font-size: 13px; color: var(--color-text); line-height: 1.3;',
    '}',
    '.ph-dot { width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; }',
    '.ph-dot.red    { background: var(--color-status-red); }',
    '.ph-dot.yellow { background: var(--color-status-yellow); }',
    '.ph-dot.blue   { background: var(--color-primary); }',
    '.ph-empty { font-size: 12px; color: var(--color-text-subtle); font-style: italic; }',

    '.ph-stacked {',
    '  display: flex; width: 100%; height: 28px;',
    '  border-radius: 6px; overflow: hidden;',
    '  background: var(--color-surface-alt);',
    '}',
    '.ph-stacked > div {',
    '  display: flex; align-items: center; justify-content: center;',
    '  color: #fff; font-size: 12px; font-weight: 600;',
    '}',
    '.ph-stacked-legend {',
    '  display: flex; gap: 16px; margin-top: 10px;',
    '  font-size: 12px; color: var(--color-text-muted); flex-wrap: wrap;',
    '}',
    '.ph-legend-swatch {',
    '  display: inline-block; width: 10px; height: 10px;',
    '  border-radius: 2px; margin-right: 6px; vertical-align: middle;',
    '}',

    '.ph-split-table { width: 100%; border-collapse: collapse; }',
    '.ph-split-table td { padding: 8px 0; vertical-align: middle; font-size: 12px; }',
    '.ph-split-table td.ph-split-label { width: 70px; font-weight: 600; }',
    '.ph-split-table td.ph-split-bars  { padding-right: 12px; }',
    '.ph-split-table tr.ph-split-totals td {',
    '  border-top: 1px solid var(--color-border);',
    '  padding-top: 10px; font-weight: 700;',
    '}',

    '.ph-bar-row { display: flex; align-items: center; gap: 8px; margin-bottom: 4px; }',
    '.ph-bar-row:last-child { margin-bottom: 0; }',
    '.ph-bar-row .ph-bar-name  { width: 170px; font-size: 11px; color: var(--color-text-muted); }',
    '.ph-bar-track {',
    '  flex: 1; height: 14px;',
    '  background: var(--color-surface-alt);',
    '  border-radius: var(--radius-sm); overflow: hidden; position: relative;',
    '}',
    '.ph-bar-fill { height: 100%; border-radius: var(--radius-sm); }',
    '.ph-bar-row .ph-bar-value { width: 86px; text-align: right; font-size: 12px; color: var(--color-text); font-weight: 600; }',

    '.ph-health-tag {',
    '  display: inline-block; font-size: 11px; font-weight: 700;',
    '  padding: 2px 8px; border-radius: var(--radius-sm);',
    '  text-transform: uppercase; letter-spacing: 0.5px;',
    '}',
    '.ph-health-tag.green  { background: var(--color-status-green-bg);  color: var(--color-status-green-fg); }',
    '.ph-health-tag.yellow { background: var(--color-status-yellow-bg); color: var(--color-status-yellow-fg); }',
    '.ph-health-tag.red    { background: var(--color-status-red-bg);    color: var(--color-status-red-fg); }',

    '.ph-footer {',
    '  display: flex; justify-content: space-between; align-items: center;',
    '  margin-top: 18px; padding: 10px 16px;',
    '  border-top: 1px solid var(--color-border);',
    '  font-size: 11px; color: var(--color-text-subtle);',
    '}',
    '.ph-footer .ph-confidential {',
    '  font-weight: 700; color: var(--color-text-muted);',
    '  letter-spacing: 0.5px; text-transform: uppercase;',
    '}',

    '@media (max-width: 900px) {',
    '  .ph-grid { grid-template-columns: 1fr; }',
    '  .ph-kpis { grid-template-columns: repeat(2, 1fr); }',
    '}',

    // =========================================================================
    // MGM / PGL — SCHEDULE PILL, DEPLOYMENT CELL
    // =========================================================================
    '.schedule-cell {',
    '  display: flex; align-items: center; gap: 4px; white-space: nowrap;',
    '}',
    '.schedule-date {',
    '  font-size: 13px; color: var(--color-text);',
    '}',
    '.survey-pill {',
    '  display: inline-block;',
    '  margin-left: 4px;',
    '  padding: 2px 6px;',
    '  border-radius: 999px;',
    '  font-size: 10px;',
    '  font-weight: 600;',
    '  line-height: 1.4;',
    '  vertical-align: middle;',
    '  cursor: default;',
    '}',
    '.survey-pill-mds-planned,',
    '.survey-pill-pgl-planned {',
    '  background: var(--color-info-banner-bg);',
    '  color: var(--color-info-banner-text);',
    '  border: 1px solid var(--color-info-banner-border);',
    '}',
    '.survey-pill-pgl-actual {',
    '  background: var(--color-status-green-bg);',
    '  color: var(--color-status-green-fg);',
    '  border: 1px solid var(--color-status-green);',
    '}',
    '.deployment-cell {',
    '  max-width: 220px;',
    '  white-space: normal;',
    '  word-wrap: break-word;',
    '}',

    '/* ── Overview Tab ──────────────────────────────────────── */',
    '.overview-section {',
    '  margin-bottom: var(--space-4);',
    '}',
    '.overview-section-title {',
    '  font-size: 0.8125rem;',
    '  font-weight: 600;',
    '  color: var(--color-text-muted);',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.05em;',
    '  margin-bottom: var(--space-2);',
    '}',
    '.overview-kpi-strip {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: var(--space-3);',
    '}',
    '.overview-kpi-card {',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-md);',
    '  padding: var(--space-3) var(--space-4);',
    '  min-width: 120px;',
    '  text-align: center;',
    '}',
    '.overview-kpi-value {',
    '  font-size: 2rem;',
    '  font-weight: 700;',
    '  line-height: 1;',
    '  color: var(--color-text-primary);',
    '}',
    '.overview-kpi-label {',
    '  font-size: 0.75rem;',
    '  color: var(--color-text-muted);',
    '  margin-top: var(--space-1);',
    '}',
    '.overview-kpi-red    .overview-kpi-value { color: var(--color-status-red-fg); }',
    '.overview-kpi-yellow .overview-kpi-value { color: var(--color-status-yellow-fg); }',
    '.overview-kpi-green  .overview-kpi-value { color: var(--color-status-green-fg); }',
    '.overview-kpi-watch  .overview-kpi-value { color: #F46821; }',

    '.overview-lists {',
    '  display: grid;',
    '  grid-template-columns: 1fr 1fr;',
    '  gap: var(--space-4);',
    '  margin-bottom: var(--space-4);',
    '}',
    '@media (max-width: 768px) {',
    '  .overview-lists { grid-template-columns: 1fr; }',
    '}',
    '.overview-list-section {',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-md);',
    '  padding: var(--space-3);',
    '}',
    '.overview-list-title {',
    '  font-size: 0.8125rem;',
    '  font-weight: 600;',
    '  color: var(--color-text-muted);',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.05em;',
    '  margin-bottom: var(--space-2);',
    '  padding-bottom: var(--space-2);',
    '  border-bottom: 1px solid var(--color-border);',
    '}',
    '.overview-list-row {',
    '  display: flex;',
    '  align-items: flex-start;',
    '  gap: var(--space-2);',
    '  padding: var(--space-2) 0;',
    '  border-bottom: 1px solid var(--color-border-subtle);',
    '}',
    '.overview-list-row:last-child { border-bottom: none; }',
    '.overview-list-main {',
    '  flex: 1;',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 2px;',
    '}',
    '.overview-list-main strong {',
    '  font-size: 0.875rem;',
    '  color: var(--color-text-primary);',
    '}',
    '.overview-list-main span {',
    '  font-size: 0.75rem;',
    '  color: var(--color-text-muted);',
    '}',
    '.overview-list-meta {',
    '  display: flex;',
    '  flex-direction: column;',
    '  align-items: flex-end;',
    '  gap: 2px;',
    '  font-size: 0.75rem;',
    '  color: var(--color-text-muted);',
    '  white-space: nowrap;',
    '}',
    '.overview-empty {',
    '  font-size: 0.875rem;',
    '  color: var(--color-text-subtle);',
    '  font-style: italic;',
    '  padding: var(--space-2) 0;',
    '}',
    '.overview-stage-strip {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: var(--space-2);',
    '}',
    '.overview-stage-item {',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-md);',
    '  padding: var(--space-2) var(--space-3);',
    '  text-align: center;',
    '  min-width: 90px;',
    '}',
    '.overview-stage-count {',
    '  font-size: 1.25rem;',
    '  font-weight: 700;',
    '  color: var(--color-text-primary);',
    '}',
    '.overview-stage-label {',
    '  font-size: 0.7rem;',
    '  color: var(--color-text-muted);',
    '  margin-top: 2px;',
    '}',

    '/* ── Executive Watch pill ──────────────────────────────── */',
    '.exec-watch-pill {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 4px;',
    '  padding: 2px 8px;',
    '  border-radius: 999px;',
    '  font-size: 0.7rem;',
    '  font-weight: 600;',
    '  background: #fff3e0;',
    '  color: #F46821;',
    '  border: 1px solid #F46821;',
    '  cursor: pointer;',
    '  margin-left: var(--space-2);',
    '  vertical-align: middle;',
    '  white-space: nowrap;',
    '}',
    '.exec-watch-pill:hover { background: #ffe0b2; }',

    '#exec-watch-modal .modal-card {',
    '  background: var(--color-surface, #ffffff);',
    '  box-shadow: 0 4px 24px rgba(0, 0, 0, 0.18);',
    '}',

    '/* ── MDS/PGL month-group layout ────────────────────────── */',
    '.mdspgl-month-groups { display: flex; flex-direction: column; gap: var(--space-4); margin-top: var(--space-4); }',

    '.mdspgl-month-card {',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-lg);',
    '  overflow: hidden;',
    '}',
    '.mdspgl-month-header {',
    '  display: flex; align-items: center; gap: var(--space-3);',
    '  padding: var(--space-3) var(--space-4);',
    '  background: var(--color-surface-subtle);',
    '  border-bottom: 1px solid var(--color-border);',
    '  flex-wrap: wrap;',
    '}',
    '.mdspgl-month-title { margin: 0; font-size: 1.05rem; font-weight: 600; color: var(--color-text); }',

    '/* Projected badge */',
    '.mdspgl-projected-badge {',
    '  margin-left: var(--space-2); font-size: 0.75rem; font-style: italic;',
    '  color: var(--color-text-muted); font-weight: 400;',
    '}',
    '.mdspgl-projected-badge.hidden { display: none; }',

    '/* Schedule timeline pills */',
    '.mdspgl-schedule-pills { display: flex; gap: var(--space-2); align-items: center; flex-wrap: wrap; }',
    '.schedule-pill {',
    '  font-size: 0.75rem; padding: 2px 8px; border-radius: 999px;',
    '  background: var(--color-surface); border: 1px solid var(--color-border);',
    '  color: var(--color-text-muted);',
    '}',
    '.schedule-pill.open  { background: #ecfeff; border-color: #67e8f9; color: #0e7490; }',
    '.schedule-pill.close { background: #fef3c7; border-color: #fcd34d; color: #92400e; }',
    '.schedule-pill.reminder { background: var(--color-surface); }',
    '.schedule-pill strong { color: inherit; }',

    '/* Count pills */',
    '.mdspgl-month-counts { margin-left: auto; display: flex; gap: var(--space-2); }',
    '.count-pill {',
    '  font-size: 0.75rem; font-weight: 600; padding: 2px 8px; border-radius: 999px;',
    '  background: #eef2ff; color: #3730a3;',
    '}',
    '.count-pill.pgl-count { background: #ecfdf5; color: #065f46; }',

    '/* Collapse toggle */',
    '.mdspgl-collapse-toggle {',
    '  background: transparent; border: none; cursor: pointer; font-size: 1rem;',
    '  color: var(--color-text-muted); padding: 4px 8px;',
    '}',
    '.mdspgl-month-card.collapsed .mdspgl-month-body { display: none; }',
    '.mdspgl-month-card.collapsed .mdspgl-collapse-toggle { transform: rotate(-90deg); }',

    '/* Body and subsections */',
    '.mdspgl-month-body { padding: var(--space-3) var(--space-4) var(--space-4) var(--space-4); }',
    '.mdspgl-subsection { margin-top: var(--space-3); }',
    '.mdspgl-subsection:first-child { margin-top: 0; }',
    '.mdspgl-subsection-title {',
    '  margin: 0 0 var(--space-2) 0; font-size: 0.875rem; font-weight: 600;',
    '  color: var(--color-text); display: flex; align-items: center; gap: var(--space-2);',
    '}',
    '.mdspgl-subsection-empty {',
    '  font-size: 0.8125rem; color: var(--color-text-subtle); font-style: italic;',
    '  padding: var(--space-2) 0;',
    '}',

    '/* Survey type pills (subsection titles) */',
    '.survey-type-pill {',
    '  font-size: 0.6875rem; font-weight: 700; letter-spacing: 0.04em;',
    '  padding: 2px 8px; border-radius: 999px;',
    '}',
    '.survey-type-pill.mds { background: #eef2ff; color: #3730a3; }',
    '.survey-type-pill.pgl { background: #ecfdf5; color: #065f46; }',

    '/* Row table */',
    '.mdspgl-row-table { width: 100%; border-collapse: collapse; font-size: 0.8125rem; }',
    '.mdspgl-row-table thead th {',
    '  text-align: left; font-weight: 600; color: var(--color-text-muted);',
    '  background: var(--color-surface-subtle); padding: 6px 10px;',
    '  border-bottom: 1px solid var(--color-border); white-space: nowrap;',
    '}',
    '.mdspgl-row-table tbody td {',
    '  padding: 8px 10px; vertical-align: top;',
    '  border-bottom: 1px solid var(--color-border);',
    '}',
    '.mdspgl-row-table tbody tr:last-child td { border-bottom: none; }',

    '/* C10: per-column cell rules (obsolete col-event-date/onethird/start removed) */',
    '.mdspgl-row-table td.col-type { width: 60px; white-space: nowrap; }',
    '.mdspgl-row-table .survey-type-pill { cursor: help; }',
    '/* C11a: Account wraps at 280px; MTP/Partner stay nowrap */',
    '.mdspgl-row-table td.col-account {',
    '  max-width: 280px; white-space: normal; word-break: normal; overflow-wrap: anywhere;',
    '}',
    '.mdspgl-row-table td.col-currentmtp,',
    '.mdspgl-row-table td.col-partner { white-space: nowrap; }',
    '.mdspgl-row-table td.col-deployment {',
    '  max-width: 240px; white-space: normal; word-break: normal; overflow-wrap: anywhere;',
    '}',
    '.mdspgl-row-table td.col-contacts {',
    '  max-width: 220px; white-space: normal; word-break: normal;',
    '  overflow-wrap: anywhere; font-size: 0.75rem; line-height: 1.4;',
    '}',

    '/* C10: partner scope toggle */',
    '.mdspgl-partner-toggle {',
    '  display: inline-flex; align-items: center; gap: 6px; cursor: pointer;',
    '  font-size: 0.8125rem; color: var(--color-text-muted);',
    '  margin: 0 var(--space-3); user-select: none;',
    '}',
    '.mdspgl-partner-toggle input[type="checkbox"] { cursor: pointer; margin: 0; }',
    '.mdspgl-partner-toggle-label { white-space: nowrap; }',

    '/* Empty horizon */',
    '.mdspgl-empty-horizon {',
    '  text-align: center; padding: var(--space-5) var(--space-4);',
    '  color: var(--color-text-subtle); font-size: 0.9375rem;',
    '}',

    '/* ── Overview Tab — Redesigned (C11b) ──────────────────────── */',
    '/* .overview-spinner-container removed in C12 — canonical .report-loading is used instead */',

    '.overview-kpi-strip {',
    '  display: grid; grid-template-columns: repeat(5, 1fr);',
    '  gap: var(--space-3); margin-bottom: var(--space-4);',
    '}',
    '.overview-kpi-tile {',
    '  background: var(--color-surface); border: 1px solid var(--color-border);',
    '  border-left-width: 4px; border-radius: var(--radius-md);',
    '  padding: var(--space-3) var(--space-4);',
    '}',
    '.overview-kpi-tile.total           { border-left-color: #94a3b8; }',
    '.overview-kpi-tile.red             { border-left-color: #ef4444; }',
    '.overview-kpi-tile.yellow          { border-left-color: #f59e0b; }',
    '.overview-kpi-tile.green           { border-left-color: #10b981; }',
    '.overview-kpi-tile.executive-watch { border-left-color: #a855f7; }',
    '.overview-kpi-value {',
    '  font-size: 1.875rem; font-weight: 700; color: var(--color-text); line-height: 1.1;',
    '}',
    '.overview-kpi-tile.red    .overview-kpi-value { color: #b91c1c; }',
    '.overview-kpi-tile.yellow .overview-kpi-value { color: #b45309; }',
    '.overview-kpi-tile.green  .overview-kpi-value { color: #047857; }',
    '.overview-kpi-tile.executive-watch .overview-kpi-value { color: #7e22ce; }',
    '.overview-kpi-label {',
    '  font-size: 0.6875rem; font-weight: 600; letter-spacing: 0.05em;',
    '  color: var(--color-text-muted); text-transform: uppercase; margin-top: 2px;',
    '}',

    '.overview-band-2 {',
    '  display: grid; grid-template-columns: 1fr 1fr;',
    '  gap: var(--space-4); margin-bottom: var(--space-4);',
    '}',
    '@media (max-width: 900px) {',
    '  .overview-band-2 { grid-template-columns: 1fr; }',
    '  .overview-kpi-strip { grid-template-columns: repeat(2, 1fr); }',
    '}',

    '.overview-card {',
    '  background: var(--color-surface); border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-lg); overflow: hidden; display: flex; flex-direction: column;',
    '}',
    '.overview-card-header {',
    '  padding: var(--space-3) var(--space-4);',
    '  background: var(--color-surface-subtle); border-bottom: 1px solid var(--color-border);',
    '}',
    '.overview-card-title { margin: 0; font-size: 0.9375rem; font-weight: 600; color: var(--color-text); }',
    '.overview-card-subtitle { font-size: 0.75rem; font-weight: 400; color: var(--color-text-muted); margin-left: var(--space-1); }',
    '.overview-card-count-pill { font-size: 0.8125rem; font-weight: 600; color: var(--color-text-muted); margin-left: var(--space-1); }',
    '.overview-card-body { flex: 1; padding: var(--space-2) 0; }',
    '.overview-card-footer { border-top: 1px solid var(--color-border); padding: var(--space-2) var(--space-4); text-align: right; }',
    '.overview-card-link { font-size: 0.8125rem; color: var(--color-accent, #3730a3); text-decoration: none; font-weight: 500; }',
    '.overview-card-link:hover { text-decoration: underline; }',

    '.overview-list-row {',
    '  display: grid; grid-template-columns: 12px 1fr auto auto;',
    '  align-items: center; gap: var(--space-3);',
    '  padding: var(--space-2) var(--space-4);',
    '  border-bottom: 1px solid var(--color-border-subtle, #f1f5f9);',
    '  cursor: pointer; transition: background 0.12s ease;',
    '}',
    '.overview-list-row:last-child { border-bottom: none; }',
    '.overview-list-row:hover { background: var(--color-surface-subtle); }',
    '.overview-health-dot { width: 10px; height: 10px; border-radius: 50%; flex-shrink: 0; }',
    '.overview-health-dot.red    { background: #ef4444; }',
    '.overview-health-dot.yellow { background: #f59e0b; }',
    '.overview-health-dot.green  { background: #10b981; }',
    '.overview-list-content { min-width: 0; overflow: hidden; }',
    '.overview-list-account { font-size: 0.8125rem; font-weight: 600; color: var(--color-text); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }',
    '.overview-list-deployment { font-size: 0.75rem; color: var(--color-text-muted); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }',
    '.overview-list-partner { font-size: 0.75rem; color: var(--color-text-muted); white-space: nowrap; }',
    '.overview-list-date { font-size: 0.8125rem; color: var(--color-text); white-space: nowrap; font-variant-numeric: tabular-nums; }',
    '.overview-empty-state { text-align: center; padding: var(--space-5) var(--space-4); color: var(--color-text-subtle); font-size: 0.8125rem; }',

    '.overview-band-3 .overview-card-header { padding-bottom: var(--space-2); }',
    '.overview-band-3 .overview-card-subtitle { display: block; margin: 4px 0 0 0; font-size: 0.75rem; color: var(--color-text-muted); }',
    '.overview-band-3 .overview-card-body { padding: var(--space-4); }',

    '.lifecycle-bar { display: flex; gap: 2px; height: 56px; border-radius: var(--radius-md); overflow: hidden; margin-bottom: var(--space-3); }',
    '.lifecycle-segment { display: flex; flex-direction: column; justify-content: center; align-items: center; color: white; min-width: 60px; padding: 0 var(--space-2); }',
    '.lifecycle-segment-count { font-size: 1.25rem; font-weight: 700; line-height: 1; }',
    '.lifecycle-segment-label { font-size: 0.6875rem; font-weight: 600; letter-spacing: 0.04em; text-transform: uppercase; margin-top: 2px; opacity: 0.92; }',
    '.lifecycle-starting { background: #93c5fd; color: #1e3a8a; }',
    '.lifecycle-building { background: #3b82f6; }',
    '.lifecycle-landing  { background: #1e40af; }',
    '.lifecycle-other    { background: #94a3b8; }',
    '.lifecycle-stage-lists { display: flex; gap: 2px; }',
    '.lifecycle-stage-list { flex: 1; font-size: 0.6875rem; color: var(--color-text-muted); padding: 0 var(--space-2); text-align: center; line-height: 1.4; }',

    /* S1: Student tab */
    '.student-health-chips { display: flex; flex-wrap: wrap; gap: var(--space-2); margin-top: var(--space-1); }',
    '.student-health-chips .status-badge { font-size: 12px; padding: 3px var(--space-2); }',
    '.student-health-chips .status-badge.chip-zero { opacity: 0.35; }',
    '.student-detail { padding: var(--space-3) var(--space-4); background: var(--color-bg-subtle, #f9fafb); border-left: 3px solid var(--color-primary, #0f4c81); font-size: 0.8125rem; line-height: 1.6; }',
    '.student-detail ul { margin: 4px 0 0 18px; padding: 0; }',
    '.student-banner { background: #e8f0fe; border-left: 4px solid #1a73e8; padding: 8px 14px; font-size: 12px; color: #174ea6; margin-bottom: 12px; border-radius: 4px; }',
    '.student-banner a { color: #1a73e8; font-weight: 600; }',

    // =========================================================================
    // P2: PORTFOLIO MOMENTUM SUB-VIEW
    // =========================================================================
    '.portfolio-subview-toggle { margin: 12px 0 16px; }',
    '.momentum-header { margin-bottom: 16px; }',
    '.momentum-title { font-size: 1.25rem; font-weight: 700; color: var(--color-text); margin: 0 0 4px; }',
    '.momentum-meta { font-size: 12px; color: var(--color-text-muted); }',
    '.momentum-kpi-strip { margin-bottom: 20px; }',
    '.momentum-chart-container {',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-md);',
    '  padding: 16px;',
    '  margin-bottom: 16px;',
    '  overflow-x: auto;',
    '}',
    '.momentum-growth-annotations {',
    '  font-size: 12px;',
    '  color: var(--color-text-muted);',
    '  background: var(--color-surface);',
    '  border: 1px solid var(--color-border);',
    '  border-radius: var(--radius-md);',
    '  padding: 12px 16px;',
    '  margin-bottom: 12px;',
    '}',
    '.momentum-growth-annotations p { margin: 2px 0; }',
    '.momentum-footer {',
    '  font-size: 11px;',
    '  font-style: italic;',
    '  color: var(--color-text-subtle);',
    '  margin-top: 4px;',
    '}'

  ].join('\n');

  return _CoreUI_Css_CACHE;
}