/**
 * Script Property keys for External Data Manager (never store values in Git).
 * @namespace EdmProperties
 */
var EdmProperties = (function () {
  'use strict';

  var EXTERNAL_DATA_PARENT_FOLDER_ID = 'EXTERNAL_DATA_PARENT_FOLDER_ID';
  var QUALTRICS_INBOX_FOLDER_ID = 'QUALTRICS_INBOX_FOLDER_ID';
  var QUALTRICS_FAILED_FOLDER_ID = 'QUALTRICS_FAILED_FOLDER_ID';
  var AUDIT_LEDGER_SPREADSHEET_ID = 'EDM_AUDIT_LEDGER_SPREADSHEET_ID';

  var DEST_HC_DM_SPREADSHEET_ID = 'EDM_DEST_HC_DM_SPREADSHEET_ID';
  var DEST_SLG_DM_SPREADSHEET_ID = 'EDM_DEST_SLG_DM_SPREADSHEET_ID';
  var DEST_HENP_DM_SPREADSHEET_ID = 'EDM_DEST_HENP_DM_SPREADSHEET_ID';

  var INGEST_ENABLED = 'EDM_QUALTRICS_INGEST_ENABLED';
  var DELETE_SUCCESSFUL_SOURCE = 'EDM_DELETE_SUCCESSFUL_QUALTRICS_SOURCE';

  return {
    EXTERNAL_DATA_PARENT_FOLDER_ID: EXTERNAL_DATA_PARENT_FOLDER_ID,
    QUALTRICS_INBOX_FOLDER_ID: QUALTRICS_INBOX_FOLDER_ID,
    QUALTRICS_FAILED_FOLDER_ID: QUALTRICS_FAILED_FOLDER_ID,
    AUDIT_LEDGER_SPREADSHEET_ID: AUDIT_LEDGER_SPREADSHEET_ID,
    DEST_HC_DM_SPREADSHEET_ID: DEST_HC_DM_SPREADSHEET_ID,
    DEST_SLG_DM_SPREADSHEET_ID: DEST_SLG_DM_SPREADSHEET_ID,
    DEST_HENP_DM_SPREADSHEET_ID: DEST_HENP_DM_SPREADSHEET_ID,
    INGEST_ENABLED: INGEST_ENABLED,
    DELETE_SUCCESSFUL_SOURCE: DELETE_SUCCESSFUL_SOURCE
  };
})();
