/**
 * EVI_DM (Evisort) App configuration for CoreLib.
 *
 * NOTE:
 *   - Assumes the Core library is added as "CoreLib" in Project → Libraries.
 *   - Reuses EVI_DM TABLES and BAR_CONFIG constants from Code.js.
 */

/** @type {AppConfig} */
var APP_CONFIG = {
  appId: 'EVI_DM',

  sheets: {
    activeDeployments:     'ActiveDeployments',
    goLives:               'Go Lives',
    deploymentOverrides:   'DeploymentOverrides',
    goLivesOverrides:      'GoLivesOverrides',
    deploymentsMeta:       'DeploymentsMeta',
    changeLog:             'ChangeLog',
    execSummary:           'ExecSummary',
    healthReportSnapshots: 'HealthReportSnapshots',
    healthMonthlySummary:  'HealthMonthlySummary',
    healthYtdSummary:      'HealthYtdSummary',
    dashboard:             'Dashboard',
    appUsers:              'AppUsers',
    ddAssignment:          'DD Assignment',
    sfdcDeploymentProductFunctions: 'SFDC_DeploymentProductFunctions',
    deployments: 'SFDC_Deployments',
    deploymentContacts: 'SFDC_DeploymentContacts',
    sfdcContacts: 'SFDC_DeploymentContacts',
    deploymentHistory: 'SFDC_DeploymentHistory'
  },

  namedRanges: {
    healthTotal: 'HealthTotal'
  },

  columns: {
    DEPLOYMENT_ID:              1,
    DEPLOYMENT_NAME:            2,
    ACCOUNT_ID:                 3,
    ACCOUNT_NAME:               4,
    INDUSTRY:                   5,
    REGION:                     6,
    SUB_REGION:                 7,
    SUB_REGION_ALT:             8,
    BILLING_STATE:              9,
    BILLING_CITY:              10,
    DEPLOYMENT_START_DATE:     11,
    CURRENT_MTP_DATE:          12,
    FIRST_MTP_DATE:            13,
    OVERALL_STATUS:            14,
    DEPLOYMENT_PHASE:          15,
    DEPLOYMENT_STAGE:          16,
    DEPLOYMENT_HEALTH:         17,
    COMPLETION_DATE:           18,
    WD_ENG_MANAGER:            19,
    DAM_FULL_NAME:             20,
    PRIMING_PARTNER:           21,
    IMPL_PARTNER:              22,
    PARTNER:                   23,
    CURRENT_DEPLOYMENT_UPDATE: 24,
    goLives: {
      ACCOUNT_NAME:        1,
      INDUSTRY:            2,
      DAM_FULL_NAME:       3,
      WD_ENG_MANAGER:      4,
      PARTNER:             5,
      DEPLOYMENT_NAME:     6,
      SERVICES_APPROACH:   7,
      PRODUCT_AREA:        8,
      GO_LIVE_DATE_ACTUAL: 9,
      IN_PRODUCTION:      10
    }
  },

  report: {
    inlineFilename:  'EVI_DeploymentHealth_Dashboard.html',
    outlookFilename: 'EVI_DeploymentHealth_Dashboard_Outlook.html',
    v2ExportFilename: 'EVI_Evisort_DeploymentHealth_Report_V2.html',

    title: 'Evisort Deployment Health Report',
    headerLogoUrl: 'https://cdn.brandfetch.io/id0V-YF4nE/w/2048/h/2048/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1761286530298',
    sanaLogoUrl:   'https://emoji.slack-edge.com/T7U335QS3/sana-labs/1746635f6808c56a.png',
    footerAttribution: 'Generated by the Evisort Program Management team',

    tables:    TABLES,
    barConfig: BAR_CONFIG,

    goLivesWindowDays: 60,
    redYellowPartnerFilter: null,
    includeIndustryRedYellow: false,
    includeIndustryGoLives:   false,
    redYellowOwnerLabel: 'Delivery Director',

    productScope: {
      enabled: true,
      includeAreas: [
        'Contract Management and Document Intelligence'
      ],
      nameTokens: [
        'Evisort',
        'CLM'
      ]
    },

    portfolioHealth: {
      title: 'Portfolio Health',
      workdayPartner: 'Workday Professional Services',
      workdayLabel: 'Workday',
      otherLabel: 'Partners/Other',
      recentGoLivesWindowDays: 60,
      industryBuckets: []
    },

    sections: { approach: true },

    distribution: {
      enabled: false,
      fromAlias: '',
      to: [],
      cc: [],
      bcc: 'jeffrey.ditty@workday.com',
      allowedSenders: ['jeffrey.ditty@workday.com'],
      subjectTemplate: 'Evisort \u2014 Monthly Deployment Health Report \u2014 {{monthLabel}}',
      logSheet: 'ReportDistributionLog'
    }
  },

  salesforce: {
    upcomingWindowDays: 90,
    recentWindowDays: 60,
    statusValues: {
      active:   'Active',
      complete: 'Complete'
    }
  },

  ui: {
    appTitle:       'Evisort Deployment Health Manager',
    headerTitle:    'Evisort Deployment Health Manager',
    headerSubtitle: 'Review and manage Evisort deployment data',

    tabs: [
      { id: 'deployments', label: 'Deployments' },
      { id: 'golives',     label: 'Go Lives' },
      { id: 'execsummary', label: 'Executive Summary' },
      { id: 'report',      label: 'Monthly Report Preview' },
      { id: 'portfolio',   label: 'Portfolio Health' },
      { id: 'mgmPgl',      label: 'MGM / PGL' },
      { id: 'notable', label: 'Notable Deployments' },
      { id: 'overrides',   label: 'Manage Overrides' }
    ],

    mgmPglTab: {
      enabled: true
    },
    trendsTab: { enabled: false },
    enableAccountLinks: true,
    deploymentsTable: {
      showIndustry: false,
      showEmColumn: false,
      ownerColumnLabel: 'Delivery Director',
      showMissingDDHighlight: true,
      missingDDMessage: 'Delivery Director needs assigned',
      searchPlaceholder: 'Search by account, deployment name, partner...',
      defaultHealthFilter: ['Red', 'Yellow'],
      showStageColumn: false,
      expandableRows: true,
      useDdFromContacts: true
    },

    goLivesTable: {
      showIndustry: false,
      showProductAreas: true,
      showDeploymentName: false,
      searchPlaceholder: 'Search by account name...'
    },

    goLivesTab: {
      defaultView: 'recent',
      recentWindowDays: 60,
      upcomingWindowDays: 90
    },

    manageOverrides: {
      showAuditTrail: true,
      bulkClearScopes: ['monthly', 'all']
    },

    editModal: {
      ownerFieldLabel: 'Delivery Director',
      ownerInputType: 'dropdown',
      ownerOptions: []
    },

    productFilter: {
      enabled: false,
      hidden: true,
      areas: [],
      aliases: {},
      nameTokens: {}
    },

    personalization: {
      enabled: false,
      defaultViewMode: 'myPortfolio',
      affectsTabs: ['deployments', 'golives', 'mgmPgl', 'overrides'],
      welcomeMessageEnabled: true,
      showFullPortfolioIndicator: true
    }
  },

  notable: {
    notify: {
      email:               'mariah.maxie@workday.com',
      testEmail:           'jeffrey.ditty@workday.com',
      useTestMode:         true,
      slackWebhookUrl:     '',
      slackWebhookUrlTest: ''
    }
  },

  notify: {
    enabled: false,
    allowedFromAliases: ['jeffrey.ditty@workday.com']
  },

  trends: {
    cacheTtlSeconds:              3600,
    trendsWindowMonths:           12,
    timeInStageOutlierMultiple:   2,
    timeInStageMinSampleSize:     10,
    byPartnerMinSampleSize:       5
  },

  momentum: {
    enabled: false
  }
};
