/**
 * Healthcare (HC) App configuration for CoreLib.
 *
 * NOTE:
 *   - Assumes the Core library is added as "CoreLib" in Project → Libraries.
 *   - Assumes HC's TABLES and BAR_CONFIG constants (from its Code.gs)
 *     are defined in this project and reused here.
 */

/** @type {AppConfig} */
var APP_CONFIG = {
  appId: 'HC',

  sheets: {
    activeDeployments:     'ActiveDeployments',
    goLives:               'Go Lives',
    deploymentOverrides:   'DeploymentOverrides',
    goLivesOverrides:      'GoLivesOverrides',
    deploymentsMeta:       'DeploymentsMeta',
    changeLog:             'ChangeLog',
    execSummary:           'ExecSummary',
    healthReportSnapshots: 'HealthReportSnapshots',
    healthMonthlySummary:  'HealthMonthlySummary',
    healthYtdSummary:      'HealthYtdSummary',
    dashboard:             'Dashboard'
  },

  namedRanges: {
    healthTotal: 'HealthTotal'
  },

  columns: {
    // HC currently shares the same column layout as SLG/HENP.
    deployments: {
      ACCOUNT_NAME: 1,  // A
      DEPLOYMENT_NAME: 2,  // B
      SERVICES_APPROACH: 3,  // C
      INDUSTRY: 4,  // D
      SUB_REGION: 5,  // E
      PARTNER: 6,  // F
      DEPLOYMENT_STAGE: 7,  // G
      DEPLOYMENT_HEALTH: 8,  // H
      CURRENT_MTP_DATE: 9,  // I
      PROF_SERVICES_LOCS: 10,  // J
      PROF_SERVICES_DETAILS: 11,  // K
      DAM_FULL_NAME: 12,  // L
      WD_ENG_MANAGER: 13,  // M
      CURRENT_DEPLOYMENT_UPDATE: 14, // N
      DEPLOYMENT_ID: 15  // O
    },
    goLives: {
      ACCOUNT_NAME: 1,  // A
      INDUSTRY: 2,  // B
      DAM_FULL_NAME: 3,  // C
      WD_ENG_MANAGER: 4,  // D
      PARTNER: 5,  // E
      DEPLOYMENT_NAME: 6,  // F
      SERVICES_APPROACH: 7,  // G
      PRODUCT_AREA: 8,  // H
      GO_LIVE_DATE_ACTUAL: 9,  // I
      IN_PRODUCTION: 10  // J
    }
  },

  report: {
    // Filenames used when exporting HTML to Drive
    inlineFilename:  'Healthcare_DeploymentHealth_Dashboard.html',
    outlookFilename: 'Healthcare_DeploymentHealth_Dashboard_Outlook.html',

    // Title and branding specific to Healthcare
    title: 'Healthcare Deployment Health Report',
    headerLogoUrl: 'https://cdn.brandfetch.io/id0V-YF4nE/w/2048/h/2048/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1761286530298',
    sanaLogoUrl:   'https://emoji.slack-edge.com/T7U335QS3/sana-labs/1746635f6808c56a.png',
    footerAttribution: 'Generated by the Healthcare Program Management team',

    // Use Healthcare’s existing TABLES / BAR_CONFIG from its Code.gs
    tables:    TABLES,
    barConfig: BAR_CONFIG,

    // Behavior flags (differences vs SLG/HENP)
    goLivesWindowDays: 60,
    redYellowPartnerFilter: null,
    includeIndustryRedYellow: false,  // HC Red/Yellow section does not show Industry
    includeIndustryGoLives:   false,  // HC Go Lives section uses Deployment Name instead

    // Portfolio Health tab (HC)
    portfolioHealth: {
      title: 'Portfolio Health',
      workdayPartner: 'Workday Professional Services',
      workdayLabel: 'Workday',
      otherLabel: 'Partners/Other',
      recentGoLivesWindowDays: 60,
      historyWindowMonths: 6,
      industryBuckets: [
        { label: 'Health Insurance',                match: ['Health Insurance'] },
        { label: 'Acute Hospital / Health System',  match: ['Acute Hospital / Health System'] },
        { label: 'Ambulatory',                      match: ['Ambulatory'] },
        { label: 'Post Acute',                      match: ['Post Acute'] },
        { label: 'Other Healthcare',                match: ['Other Healthcare'] }
      ]
    }
  },

  // ---------------------------------------------------------------------------
  // UI configuration (Phase 0). Consumed by CoreLib.CoreUI.
  // ---------------------------------------------------------------------------
  ui: {
    appTitle:       'Healthcare Deployment Health Manager',
    headerTitle:    'Healthcare Deployment Health Manager',
    headerSubtitle: 'Review and manage deployment data across all stages',

    tabs: [
      { id: 'deployments', label: 'Red & Yellow Deployments' },
      { id: 'golives',     label: 'Recent Go Lives (60 days)' },
      { id: 'upcoming',    label: 'Upcoming Go Lives (90 days)' },
      { id: 'execsummary', label: 'Executive Summary' },
      { id: 'report',      label: 'Monthly Report Preview' },
      { id: 'portfolio',   label: 'Portfolio Health' }
    ],

    deploymentsTable: {
      showIndustry: false,           // HC: no Industry column
      showEmColumn: true,            // HC: shows EM column
      ownerColumnLabel: 'EM',
      showMissingDDHighlight: false, // HC: no missing-DD row highlight
      missingDDMessage: 'Delivery Director needs assigned',  // unused for HC
      searchPlaceholder: 'Search by account, deployment name, partner...'
    },

    goLivesTable: {
      showIndustry: false,
      showProductAreas: false,       // HC: Go Lives shows Deployment Name instead
      showDeploymentName: true,
      searchPlaceholder: 'Search by account name...'
    },

    upcomingTable: {
      showIndustry: false,
      showProductAreas: false,
      showDeploymentName: true,
      searchPlaceholder: 'Search by account name...'
    },

    editModal: {
      ownerFieldLabel: 'Delivery Director',
      ownerInputType: 'dropdown',
      // Phase 0: preserved exactly as in HC production (likely-stale SLG names).
      // Will be revisited in Phase 1 when HC's real DD/EM list is finalized.
      ownerOptions: ['Steve Rogers', 'Roman Cortes', 'Lakshmi Visvanathan']
    },

    personalization: {
      enabled: false,
      defaultViewMode: 'myPortfolio',
      affectsTabs: ['deployments', 'golives', 'upcoming', 'trends', 'overrides'],
      welcomeMessageEnabled: true,
      showFullPortfolioIndicator: true
    }
  }
};