/**
 * Healthcare (HC) App configuration for CoreLib.
 *
 * Phase 3j + Stage 1: SFDC-first effective deployments + role-based access.
 *  - cfg.sheets.deployments = 'SFDC_Deployments' (canonical source via SOQL)
 *  - cfg.columns.deployments aligned to HC's SFDC_Deployments column positions
 *    (NOTE: HC has 14 columns, not 16 — Priming/Implementation Partner are
 *    omitted from HC's SOQL, so Deployment_Partner_Name__c lands at col 14.)
 *  - SOQL-side filtering enforces industry, region, status, and phase
 *    exclusions; APP_CONFIG just registers sheet/columns.
 *
 * NOTE:
 *  - Assumes the Core library is added as "CoreLib" in Project → Libraries.
 *  - Assumes HC's TABLES and BAR_CONFIG constants (from its Code.gs)
 *    are defined in this project and reused here.
 */

/** @type {AppConfig} */
var APP_CONFIG = {
  appId: 'HC',

  sheets: {
    activeDeployments:                'ActiveDeployments',
    goLives:                          'Go Lives',
    deploymentOverrides:              'DeploymentOverrides',
    goLivesOverrides:                 'GoLivesOverrides',
    deploymentsMeta:                  'DeploymentsMeta',
    changeLog:                        'ChangeLog',
    execSummary:                      'ExecSummary',
    healthReportSnapshots:            'HealthReportSnapshots',
    healthMonthlySummary:             'HealthMonthlySummary',
    healthYtdSummary:                 'HealthYtdSummary',
    dashboard:                        'Dashboard',
    appUsers:                         'AppUsers',
    ddAssignment:                     'DD',
    sfdcDeploymentProductFunctions:   'SFDC_DeploymentProductFunctions',
    deployments:                      'SFDC_Deployments',
    deploymentContacts:               'SFDC_DeploymentContacts'
  },

  namedRanges: {
    healthTotal: 'HealthTotal'
  },

  columns: {
    DEPLOYMENT_ID:              1,
    DEPLOYMENT_NAME:            2,
    ACCOUNT_ID:                 3,
    ACCOUNT_NAME:               4,
    INDUSTRY:                   5,
    REGION:                     6,
    SUB_REGION:                 7,
    SUB_REGION_ALT:             8,
    BILLING_STATE:              9,
    BILLING_CITY:              10,
    DEPLOYMENT_START_DATE:     11,
    CURRENT_MTP_DATE:          12,
    FIRST_MTP_DATE:            13,
    OVERALL_STATUS:            14,
    DEPLOYMENT_PHASE:          15,
    DEPLOYMENT_STAGE:          16,
    DEPLOYMENT_HEALTH:         17,
    COMPLETION_DATE:           18,
    WD_ENG_MANAGER:            19,
    DAM_FULL_NAME:             20,
    PRIMING_PARTNER:           21,
    IMPL_PARTNER:              22,
    PARTNER:                   23,
    CURRENT_DEPLOYMENT_UPDATE: 24,
    goLives: {
      ACCOUNT_NAME:        1,
      INDUSTRY:            2,
      DAM_FULL_NAME:       3,
      WD_ENG_MANAGER:      4,
      PARTNER:             5,
      DEPLOYMENT_NAME:     6,
      SERVICES_APPROACH:   7,
      PRODUCT_AREA:        8,
      GO_LIVE_DATE_ACTUAL: 9,
      IN_PRODUCTION:      10
    }
  },

  report: {
    inlineFilename:    'Healthcare_DeploymentHealth_Dashboard.html',
    outlookFilename:   'Healthcare_DeploymentHealth_Dashboard_Outlook.html',
    title:             'Healthcare Deployment Health Report',
    headerLogoUrl:     'https://cdn.brandfetch.io/id0V-YF4nE/w/2048/h/2048/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1761286530298',
    sanaLogoUrl:       'https://emoji.slack-edge.com/T7U335QS3/sana-labs/1746635f6808c56a.png',
    footerAttribution: 'Generated by the Healthcare Program Management team',
    tables:            TABLES,
    barConfig:         BAR_CONFIG,

    goLivesWindowDays:        60,
    redYellowPartnerFilter:   null,
    includeIndustryRedYellow: false,
    includeIndustryGoLives:   false,
    redYellowOwnerLabel:      'EM',

    portfolioHealth: {
      title:                   'Portfolio Health',
      workdayPartner:          'Workday Professional Services',
      workdayLabel:            'Workday',
      otherLabel:              'Partners/Other',
      recentGoLivesWindowDays: 60,
      historyWindowMonths:     6,
      industryBuckets: [
        { label: 'Health Insurance',               match: ['Health Insurance'] },
        { label: 'Acute Hospital / Health System', match: ['Acute Hospital / Health System'] },
        { label: 'Ambulatory',                     match: ['Ambulatory'] },
        { label: 'Post Acute',                     match: ['Post Acute'] },
        { label: 'Other Healthcare',               match: ['Other Healthcare'] }
      ]
    }
  },

  salesforce: {
    upcomingWindowDays: 90,
    recentWindowDays:   60,
    statusValues: {
      active:   'Active',
      complete: 'Complete'
    }
  },

  ui: {
    appTitle:       'Healthcare Deployment Health Manager',
    headerTitle:    'Healthcare Deployment Health Manager',
    headerSubtitle: 'Review and manage deployment data across all stages',

    // v2 consolidated tab structure (matches HENP/SLG).
    tabs: [
      { id: 'deployments', label: 'Deployments' },
      { id: 'golives',     label: 'Go Lives' },
      { id: 'execsummary', label: 'Executive Summary' },
      { id: 'report',      label: 'Monthly Report Preview' },
      { id: 'portfolio',   label: 'Portfolio Health' },
      { id: 'mgmPgl',      label: 'MGM / PGL' },
      { id: 'notable', label: 'Notable Deployments' },
      { id: 'overrides',   label: 'Manage Overrides' }
    ],
    enableAccountLinks: true,
    mgmPglTab: { enabled: true },

    deploymentsTable: {
      showIndustry:           false,
      showEmColumn:           true,    // HC: shows EM column
      ownerColumnLabel:       'EM',
      showMissingDDHighlight: false,   // HC: no missing-DD highlight
      missingDDMessage:       'Delivery Director needs assigned',
      searchPlaceholder:      'Search by account, deployment name, partner...',
      defaultHealthFilter:    ['Red', 'Yellow'],
      showStageColumn:        false,
      expandableRows:         true
    },

    goLivesTable: {
      showIndustry:        false,
      showProductAreas:    false,   // HC shows Deployment Name instead
      showDeploymentName:  true,
      searchPlaceholder:   'Search by account name...'
    },

    goLivesTab: {
      defaultView:        'recent',
      recentWindowDays:   60,
      upcomingWindowDays: 90
    },

    manageOverrides: {
      showAuditTrail:   true,
      bulkClearScopes:  ['monthly', 'all']
    },

    editModal: {
      ownerFieldLabel: 'EM',
      ownerInputType:  'text',     // Phase 3j: drop the stale SLG dropdown options
      ownerOptions:    []
    },

    personalization: {
      enabled:                    false,
      defaultViewMode:            'allDeployments',
      affectsTabs:                ['deployments', 'golives', 'overrides'],
      welcomeMessageEnabled:      false,
      showFullPortfolioIndicator: true
    }
  },

  notable: {
    notify: {
      email:               'mariah.maxie@workday.com',
      testEmail:           'jeffrey.ditty@workday.com',
      useTestMode:         true,
      slackWebhookUrl:     '',
      slackWebhookUrlTest: ''
    }
  },

  // ---------------------------------------------------------------------------
  // P2: Portfolio Momentum sub-view configuration.
  // ---------------------------------------------------------------------------
  /** @type {MomentumConfig} */
  momentum: {
    enabled: true,
    platforms: ['HCM', 'FIN', 'PAY'],
    productAreaMapping: {
      HCM: ['Core HCM', 'Human Capital Management'],
      FIN: ['Financials', 'Financial Management'],
      PAY: ['Payroll']
    },
    historicalYears: 5,  // was 6 — reduced to drop FY21 (incomplete SOQL data)
    chart: {
      colors: {
        HCM: '#0F4C81',
        FIN: '#F46821',
        PAY: '#47E6C1'
      },
      inProgressOpacity: 0.55
    }
  }
};