/**
 * SLG App configuration for CoreLib.
 *
 * Phase history:
 *   Phase 0 (v8): introduced cfg.ui block with header, tabs, table config, etc.
 *   Phase 1 (v9): tab labels harmonized to canonical Phase 1 forms.
 *   Phase 2 (v10): tab structure restructured (Deployments rename, Go Lives
 *                  consolidation, Manage Overrides added); personalization
 *                  enabled; new goLivesTab, manageOverrides blocks; deployments
 *                  table gains expandable rows and default Health filter preset.
 *   Phase 3a (v11): salesforce block added; SFDC_DeploymentProductFunctions
 *                   sheet registered; isPhased / upcomingDates enrichment
 *                   flows through CoreData → UI.
 *
 * NOTE:
 *   - Assumes the Core library is added as "CoreLib" in Project → Libraries.
 *   - Reuses SLG's existing TABLES and BAR_CONFIG constants from Code.gs.
 *   - Phase 2 personalization requires AppUsers and DD Assignment sheets in
 *     the SLG Google Sheet (created manually by Jeff).
 */

/** @type {AppConfig} */
var APP_CONFIG = {
  appId: 'SLG',

  sheets: {
    activeDeployments:     'ActiveDeployments',
    goLives:               'Go Lives',
    deploymentOverrides:   'DeploymentOverrides',
    goLivesOverrides:      'GoLivesOverrides',
    deploymentsMeta:       'DeploymentsMeta',
    changeLog:             'ChangeLog',
    execSummary:           'ExecSummary',
    healthReportSnapshots: 'HealthReportSnapshots',
    healthMonthlySummary:  'HealthMonthlySummary',
    healthYtdSummary:      'HealthYtdSummary',
    dashboard:             'Dashboard',
    // Phase 2 sheets
    appUsers:              'AppUsers',
    ddAssignment:          'DD Assignment',
    // Phase 3a: Salesforce deployment product-function detail
    sfdcDeploymentProductFunctions: 'SFDC_DeploymentProductFunctions'
  },

  namedRanges: {
    healthTotal: 'HealthTotal'
  },

  columns: {
    deployments: {
      ACCOUNT_NAME: 1,  // A
      DEPLOYMENT_NAME: 2,  // B
      SERVICES_APPROACH: 3,  // C
      INDUSTRY: 4,  // D
      SUB_REGION: 5,  // E
      PARTNER: 6,  // F
      DEPLOYMENT_STAGE: 7,  // G
      DEPLOYMENT_HEALTH: 8,  // H
      CURRENT_MTP_DATE: 9,  // I
      PROF_SERVICES_LOCS: 10,  // J
      PROF_SERVICES_DETAILS: 11,  // K
      DAM_FULL_NAME: 12,  // L
      WD_ENG_MANAGER: 13,  // M
      CURRENT_DEPLOYMENT_UPDATE: 14, // N
      DEPLOYMENT_ID: 15  // O
    },
    goLives: {
      ACCOUNT_NAME: 1,  // A
      INDUSTRY: 2,  // B
      DAM_FULL_NAME: 3,  // C
      WD_ENG_MANAGER: 4,  // D
      PARTNER: 5,  // E
      DEPLOYMENT_NAME: 6,  // F
      SERVICES_APPROACH: 7,  // G
      PRODUCT_AREA: 8,  // H
      GO_LIVE_DATE_ACTUAL: 9,  // I
      IN_PRODUCTION: 10  // J
    }
  },

  report: {
    inlineFilename:  'SLG_DeploymentHealth_Dashboard.html',
    outlookFilename: 'SLG_DeploymentHealth_Dashboard_Outlook.html',

    title: 'State & Local Government Deployment Health Report',
    headerLogoUrl: 'https://cdn.brandfetch.io/id0V-YF4nE/w/2048/h/2048/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1761286530298',
    sanaLogoUrl:   'https://emoji.slack-edge.com/T7U335QS3/sana-labs/1746635f6808c56a.png',
    footerAttribution: 'Generated by the SLG Program Management team',

    tables:    TABLES,
    barConfig: BAR_CONFIG,

    goLivesWindowDays: 60,
    redYellowPartnerFilter: null,
    includeIndustryRedYellow: false,
    includeIndustryGoLives:   false,

    portfolioHealth: {
      title: 'Portfolio Health',
      workdayPartner: 'Workday Professional Services',
      workdayLabel: 'Workday',
      otherLabel: 'Partners/Other',
      recentGoLivesWindowDays: 60,
      industryBuckets: [
        { label: 'SLG',               match: ['State & Local Government'] },
        { label: 'Special Districts', match: ['Special Districts'] }
      ]
    }
  },

  // ---------------------------------------------------------------------------
  // Salesforce enrichment (Phase 3a). Consumed by CoreLib.CoreSalesforce.
  // upcomingWindowDays: how far ahead to look for product go-live dates.
  // ---------------------------------------------------------------------------
  salesforce: {
    upcomingWindowDays: 90
  },

  // ---------------------------------------------------------------------------
  // UI configuration (Phase 2). Consumed by CoreLib.CoreUI.
  // ---------------------------------------------------------------------------
  ui: {
    appTitle:       'SLG Deployment Health Manager',
    headerTitle:    'SLG Deployment Health Manager',
    headerSubtitle: 'Review and manage deployment data across all stages',

    // Phase 2 canonical tab structure. Note: 'upcoming' tab removed (merged
    // into 'golives'); 'overrides' tab added at end.
    tabs: [
      { id: 'deployments', label: 'Deployments' },
      { id: 'golives',     label: 'Go Lives' },
      { id: 'execsummary', label: 'Executive Summary' },
      { id: 'report',      label: 'Monthly Report Preview' },
      { id: 'portfolio',   label: 'Portfolio Health' },
      { id: 'overrides',   label: 'Manage Overrides' }
    ],

    deploymentsTable: {
      showIndustry: false,
      showEmColumn: false,
      ownerColumnLabel: 'Delivery Director',
      showMissingDDHighlight: true,
      missingDDMessage: 'Delivery Director needs assigned',
      searchPlaceholder: 'Search by account, deployment name, partner...',
      // Phase 2 additions
      defaultHealthFilter: ['Red', 'Yellow'],
      showStageColumn: false,
      expandableRows: true
    },

    // Phase 2: per-row visual config for the Go Lives table (preserves the
    // existing Phase 1 shape). Tab-level config lives in goLivesTab below.
    goLivesTable: {
      showIndustry: false,
      showProductAreas: true,
      showDeploymentName: false,
      searchPlaceholder: 'Search by account name...'
    },

    // Phase 2: consolidated Go Lives tab settings
    goLivesTab: {
      defaultView: 'recent',
      recentWindowDays: 60,
      upcomingWindowDays: 90
    },

    // Phase 2: Manage Overrides tab settings
    manageOverrides: {
      showAuditTrail: true,
      bulkClearScopes: ['monthly', 'all']
    },

    editModal: {
      ownerFieldLabel: 'Delivery Director',
      ownerInputType: 'dropdown',
      ownerOptions: ['Steve Rogers', 'Roman Cortes', 'Lakshmi Visvanathan']
    },

    // Phase 2: personalization activated
    personalization: {
      enabled: true,
      defaultViewMode: 'myPortfolio',
      affectsTabs: ['deployments', 'golives', 'overrides'],
      welcomeMessageEnabled: true,
      showFullPortfolioIndicator: true
    }
  }
};